Repository appsignal/appsignal-ruby, pull requests merged in 2018-10, with the labels that each got.

#431 Improve the installation script for Rails
  lib/appsignal/cli/install.rb
Labels: enhancement

#433 Remove unused extension send_params option
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: chore

#434 Link gcc to extension .so library
  ext/extconf.rb
  lib/appsignal/system.rb
  spec/lib/appsignal/system_spec.rb
Labels: bug

#436 Add new agent & extension diagnose report keys
  ext/agent.yml
  lib/appsignal/cli/diagnose.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/lib/appsignal/extension_spec.rb
Labels: chore

#437 Group extension and agent tests in diagnose output
  lib/appsignal/cli/diagnose.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
Labels: enhancement

#438 Add diagnose command --[no-]send-report option
  lib/appsignal/cli.rb
  lib/appsignal/cli/diagnose.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
Labels: enhancement
