Repository appsignal/appsignal-ruby, pull requests merged in 2018-09, with the labels that each got.

#426 Add error message for unsupported architectures
  ext/Rakefile
  ext/base.rb
  ext/extconf.rb
Labels: bug

#427 Use key? method rather than keys.include?
  ext/base.rb
Labels: chore

#429 Improve performance when garbage collection profiling is disabled
  lib/appsignal/garbage_collection_profiler.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/garbage_collection_profiler_spec.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: enhancement
