Repository appsignal/appsignal-ruby, pull requests merged in 2018-05, with the labels that each got.

#398 Custom metrics accept third argument with tags.
  ext/agent.yml
  ext/appsignal_extension.c
  lib/appsignal.rb
  lib/appsignal/extension/jruby.rb
  spec/lib/appsignal/extension_spec.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#404 Remove default hostname
  lib/appsignal/config.rb
  spec/lib/appsignal/auth_check_spec.rb
  spec/lib/appsignal/config_spec.rb
Labels: chore

#409 Add APPSIGNAL_FILTER_SESSION_DATA env config
  lib/appsignal/config.rb
Labels: bug

#406 Explicit header whitelist in configuration
  lib/appsignal/cli/install.rb
  lib/appsignal/config.rb
  resources/appsignal.yml.erb
  spec/lib/appsignal/cli/install_spec.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/std_streams_helper.rb
  spec/support/project_fixture/config/appsignal.yml
Labels: feature

#410 Don't suggest request headers on install
  lib/appsignal/cli/install.rb
  lib/appsignal/config.rb
  lib/appsignal/transaction.rb
  resources/appsignal.yml.erb
  spec/lib/appsignal/cli/install_spec.rb
  spec/lib/appsignal/config_spec.rb
Labels: chore

#411 Bump agent to e509c90
  ext/agent.yml
Labels: bug

#412 Fix various RuboCop violations
  .rubocop_todo.yml
  lib/appsignal.rb
  lib/appsignal/cli/install.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/lib/appsignal/cli/helpers_spec.rb
  spec/lib/appsignal/cli/install_spec.rb
  spec/support/helpers/cli_helpers.rb
Labels: chore, dev happiness

#416 Fix in memory logger initialization
  lib/appsignal.rb
Labels: bug
