Repository appsignal/appsignal-ruby, pull requests merged in 2018-04, with the labels that each got.

#393 Improve padrino action names
  lib/appsignal/integrations/padrino.rb
  spec/lib/appsignal/integrations/padrino_spec.rb
Labels: bug

#396 Add Ruby 2.5 to the TravisCI build
  .travis.yml
Labels: chore

#397 Refactor event_formatter registration code
  lib/appsignal.rb
  lib/appsignal/event_formatter.rb
  lib/appsignal/event_formatter/action_view/render_formatter.rb
  lib/appsignal/event_formatter/active_record/instantiation_formatter.rb
  lib/appsignal/event_formatter/active_record/sql_formatter.rb
  lib/appsignal/event_formatter/elastic_search/search_formatter.rb
  lib/appsignal/event_formatter/faraday/request_formatter.rb
  lib/appsignal/event_formatter/moped/query_formatter.rb
  spec/lib/appsignal/event_formatter_spec.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#401 Fix Sidekiq action names containing arguments
  CHANGELOG.md
  lib/appsignal/hooks/sidekiq.rb
  lib/appsignal/version.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
Labels: bug, support

#402 Add filter_session_data config option
  lib/appsignal/config.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: feature
