Repository appsignal/appsignal-ruby, pull requests merged in 2019-08, with the labels that each got.

#553 Fix Sequel install hook version detection mismatch.
  lib/appsignal/hooks/sequel.rb
Labels: bug

#551 Color diagnose environment warning in red
  lib/appsignal/cli.rb
  lib/appsignal/cli/diagnose.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/support/helpers/cli_helpers.rb
Labels: enhancement

#554 Test against Rails 6 final
  build_matrix.yml
  gemfiles/rails-6.0.gemfile
Labels: chore

#555 Improve support for older Sidekiq versions
  lib/appsignal/hooks/sidekiq.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
Labels: bug
