Repository appsignal/appsignal-ruby, pull requests merged in 2019-06, with the labels that each got.

#531 Remove __dir__ usage from extension installation
  ext/base.rb
Labels: bug

#532 Fix error in AS when transaction get completed
  lib/appsignal/hooks/active_support_notifications.rb
  spec/lib/appsignal/hooks/active_support_notifications_spec.rb
Labels: bug

#533 Make lambda style Ruby 1.9 compatible
  .rubocop.yml
  Rakefile
  spec/lib/appsignal/minutely_spec.rb
Labels: chore

#536 Add AppSignal transaction test helpers
  spec/lib/appsignal/hooks/action_cable_spec.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
  spec/lib/appsignal/integrations/que_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
  spec/spec_helper.rb
  spec/support/helpers/transaction_helpers.rb
  spec/support/testing.rb
Labels: chore, dev happiness

#537 Fix Object integration specs
  spec/lib/appsignal/integrations/object_spec.rb
Labels: chore

#538 Keep track of created transactions in test suite
  spec/lib/appsignal/hooks/rake_spec.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
  spec/lib/appsignal/integrations/que_spec.rb
  spec/lib/appsignal/integrations/resque_active_job_spec.rb
  spec/lib/appsignal/integrations/resque_spec.rb
  spec/spec_helper.rb
  spec/support/helpers/transaction_helpers.rb
  spec/support/testing.rb
Labels: chore, dev happiness

#539 Assert if transactions were completed
  spec/lib/appsignal/hooks/rake_spec.rb
  spec/lib/appsignal/integrations/que_spec.rb
  spec/lib/appsignal/integrations/resque_spec.rb
  spec/support/matchers/be_completed.rb
  spec/support/testing.rb
Labels: chore, dev happiness

#541 Fix Rakefile loading on Ruby 1.9.3
  Rakefile
Labels: chore

#543 Use base namespace to check Redis version
  lib/appsignal/hooks/sidekiq.rb
Labels: bug

#545 Deprecate notify_of_deploy command
  lib/appsignal/cli/notify_of_deploy.rb
  spec/lib/appsignal/cli/notify_of_deploy_spec.rb
Labels: chore

#544 Add more logging for errors in debug mode
  lib/appsignal/hooks.rb
  lib/appsignal/minutely.rb
  spec/lib/appsignal/hooks_spec.rb
  spec/lib/appsignal/minutely_spec.rb
Labels: chore

#547 In monitor_transaction, call the block always
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
Labels: bug

#548 Improve Puma compatibility
  lib/appsignal/hooks/puma.rb
  spec/lib/appsignal/hooks/puma_spec.rb
Labels: bug
