Repository appsignal/appsignal-ruby, pull requests merged in 2019-01, with the labels that each got.

#451 Remove diagnose command bundler dependency
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/cli/diagnose/paths.rb
  spec/lib/appsignal/cli/diagnose/paths_spec.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
Labels: bug

#459 Build custom .travis.yml
  .travis.yml
  Rakefile
  build_matrix.yml
  gemfiles/rails-5.2.gemfile
  support/bundler_wrapper
  support/install_deps
Labels: chore, dev happiness

#450 Store extension installation details in report
  .gitignore
  .travis.yml
  Rakefile
  build_matrix.yml
  ext/Rakefile
  ext/base.rb
  ext/extconf.rb
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/cli/diagnose/paths.rb
  lib/appsignal/extension.rb
  lib/appsignal/system.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/lib/appsignal/system_spec.rb
Labels: enhancement

#460 Test against Rails 6 beta
  .travis.yml
  build_matrix.yml
  gemfiles/rails-6.0.gemfile
Labels: chore

#463 Fix DelayedJob name extraction
  lib/appsignal/hooks.rb
  lib/appsignal/integrations/delayed_job_plugin.rb
  spec/lib/appsignal/hooks/delayed_job_spec.rb
  spec/lib/appsignal/hooks_spec.rb
Labels: bug
