Repository appsignal/appsignal-ruby, pull requests merged in 2019-09, with the labels that each got.

#556 Bump yard gem to 0.9.20
  appsignal.gemspec
Labels: security

#558 Allow archive to be downloaded from multiple mirrors
  ext/Rakefile
  ext/agent.yml
  ext/base.rb
  ext/extconf.rb
Labels: enhancement

#557 Make sure Que integration works with upcoming release
  .travis.yml
  build_matrix.yml
  gemfiles/que_beta.gemfile
  lib/appsignal/integrations/que.rb
Labels: enhancement

#561 Test on Ruby 2.6.4
  .travis.yml
  build_matrix.yml
Labels: chore

#563 Update RSpec to 3.8
  appsignal.gemspec
Labels: chore, dev happiness

#565 Check set_error arguments for Exceptions
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
Labels: bug
