Repository appsignal/appsignal-ruby, pull requests merged in 2019-03, with the labels that each got.

#483 Fix rails6 deprecation warning parent_name
  lib/appsignal/integrations/railtie.rb
Labels: chore

#484 Move Rails name helper to a helper module
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/cli/helpers.rb
  lib/appsignal/cli/install.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/utils/rails_helper.rb
Labels: chore

#487 Move instrumentation & metrics helpers to modules
  .rubocop_todo.yml
  lib/appsignal.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/helpers/metrics.rb
Labels: chore, dev happiness

#490 Refactor EventFormatter specs
  spec/lib/appsignal/event_formatter_spec.rb
  spec/support/helpers/log_helpers.rb
Labels: chore, dev happiness

#488 Add Puma minutely probe
  lib/appsignal/hooks/puma.rb
  spec/lib/appsignal/hooks/puma_spec.rb
Labels: enhancement

#491 Log invalid EventFormatter registrations as errors
  lib/appsignal/event_formatter.rb
  spec/lib/appsignal/event_formatter_spec.rb
Labels: enhancement

#492 Use guards for checks rather than if-statements
  .rubocop_todo.yml
  lib/appsignal.rb
  lib/appsignal/event_formatter.rb
  lib/appsignal/event_formatter/moped/query_formatter.rb
  lib/appsignal/hooks.rb
  lib/appsignal/marker.rb
  spec/lib/appsignal/event_formatter/moped/query_formatter_spec.rb
  spec/lib/appsignal/event_formatter_spec.rb
Labels: chore, dev happiness

#496 Fix Puma.stats calls
  lib/appsignal/hooks/puma.rb
  spec/lib/appsignal/hooks/puma_spec.rb
Labels: bug

#497 Only send Puma metrics if available
  lib/appsignal/hooks/puma.rb
  spec/lib/appsignal/hooks/puma_spec.rb
Labels: bug

#499 Bump agent to d8dc806
  ext/agent.yml
Labels: feature

#498 Update local build test script
  .gitignore
  .travis.yml
  README.md
  Rakefile
  build_matrix.yml
  gemfiles/capistrano2.gemfile
  gemfiles/capistrano3.gemfile
  gemfiles/grape.gemfile
  gemfiles/no_dependencies.gemfile
  gemfiles/padrino.gemfile
  gemfiles/que.gemfile
  gemfiles/rails-3.2.gemfile
  gemfiles/rails-4.0.gemfile
  gemfiles/rails-4.1.gemfile
  gemfiles/rails-4.2.gemfile
  gemfiles/resque.gemfile
Labels: chore, dev happiness

#501 Remove GCProbe
  lib/appsignal.rb
  lib/appsignal/minutely.rb
  spec/lib/appsignal/minutely_spec.rb
  spec/lib/appsignal_spec.rb
Labels: chore
