Repository appsignal/appsignal-ruby, pull requests merged in 2019-11, with the labels that each got.

#570 Add Puma plugin to start probe in main process
  lib/appsignal/hooks/puma.rb
  lib/puma/plugin/appsignal.rb
  spec/lib/appsignal/hooks/puma_spec.rb
  spec/lib/appsignal/minutely_spec.rb
  spec/lib/puma/appsignal_spec.rb
  spec/support/helpers/wait_for_helper.rb
  spec/support/mocks/mock_probe.rb
Labels: bug

#571 Add transaction debug mode to config
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: enhancement

#572 Deprecate JSExceptionCatcher
  lib/appsignal/rack/js_exception_catcher.rb
  spec/lib/appsignal/rack/js_exception_catcher_spec.rb
Labels: chore
