Repository appsignal/appsignal-ruby, pull requests merged in 2019-02, with the labels that each got.

#466 Refactor Utils specs
  spec/lib/appsignal/utils/hash_sanitizer_spec.rb
  spec/lib/appsignal/utils/json_spec.rb
Labels: chore, dev happiness

#467 Minutely probes update
  lib/appsignal/minutely.rb
  spec/lib/appsignal/minutely_spec.rb
Labels: enhancement

#469 Ensure only one Minutely thread can run at a time
  lib/appsignal/minutely.rb
  spec/lib/appsignal/minutely_spec.rb
Labels: chore

#473 Change probe registration method to use names
  lib/appsignal.rb
  lib/appsignal/minutely.rb
  spec/lib/appsignal/minutely_spec.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#474 Allow classes to be registered as probes
  lib/appsignal/minutely.rb
  spec/lib/appsignal/minutely_spec.rb
Labels: enhancement

#475 Enable minutely probes by default
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: enhancement

#476 Ensure the minutely probe is stopped during tests
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/minutely_spec.rb
  spec/lib/appsignal_spec.rb
  spec/spec_helper.rb
  spec/support/project_fixture/config/appsignal.yml
Labels: chore

#468 Add default Sidekiq metrics
  lib/appsignal/hooks/sidekiq.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
  spec/support/stubs/sidekiq/api.rb
Labels: feature

#472 Emit Mongoid metric to track overall query durations
  lib/appsignal/integrations/mongo_ruby_driver.rb
  spec/lib/appsignal/integrations/mongo_ruby_driver_spec.rb
Labels: enhancement

#479 Fix YAML deprecation warning
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/cli/diagnose/utils.rb
Labels: chore

#478 Fix Rails6 deprecation warning
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/cli/helpers.rb
  lib/appsignal/cli/install.rb
  spec/lib/appsignal/cli/install_spec.rb
Labels: chore

#481 Support send_error to yield the transaction
  lib/appsignal.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#480 Fix Ruby 2.6 ERB deprecation warnings
  lib/appsignal/cli/helpers.rb
  lib/appsignal/cli/install.rb
Labels: chore

#482 Fix Transaction.pause!
  lib/appsignal.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
Labels: bug
