Repository appsignal/appsignal-ruby, pull requests merged in 2019-04, with the labels that each got.

#495 Log error backtraces in minutely probes
  lib/appsignal/minutely.rb
  spec/lib/appsignal/minutely_spec.rb
Labels: chore

#504 Don't add cluster behavior in Puma single mode
  lib/appsignal/hooks/puma.rb
  spec/lib/appsignal/hooks/puma_spec.rb
Labels: bug

#503 Only register ActionView event formatter in Rails
  lib/appsignal/event_formatter/action_view/render_formatter.rb
  spec/lib/appsignal/event_formatter/action_view/render_formatter_spec.rb
Labels: bug

#505 Convert Sidekiq latency from seconds to ms
  lib/appsignal/hooks/sidekiq.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
Labels: bug

#506 Rename PLATFORM constant for JRuby installation
  ext/base.rb
  ext/extconf.rb
Labels: chore

#508 Log hostname in Sidekiq probe
  lib/appsignal/hooks/sidekiq.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
Labels: chore

#511 Wait with the initial minutely probe run
  lib/appsignal/minutely.rb
  spec/lib/appsignal/minutely_spec.rb
Labels: enhancement

#513 Fix brittle method call assertions in threads
  spec/lib/appsignal/minutely_spec.rb
Labels: bug

#514 Remove unused docker cgroup fixtures
  spec/support/fixtures/containers/cgroups/docker
  spec/support/fixtures/containers/cgroups/docker_systemd
  spec/support/fixtures/containers/cgroups/lxc
  spec/support/fixtures/containers/cgroups/no_permission
  spec/support/fixtures/containers/cgroups/none
Labels: chore

#512 Link to the diagnose documentation from the demo error message
  lib/appsignal/cli/demo.rb
Labels: enhancement

#515 Move project fixture config files
  spec/lib/appsignal/config_spec.rb
  spec/support/fixtures/projects/valid/config/application.rb
  spec/support/fixtures/projects/valid/config/appsignal.yml
  spec/support/fixtures/projects/valid/config/environments/development.rb
  spec/support/fixtures/projects/valid/config/environments/production.rb
  spec/support/fixtures/projects/valid/config/environments/test.rb
  spec/support/fixtures/projects/valid/log/.gitkeep
  spec/support/helpers/config_helpers.rb
Labels: chore

#516 Fix Bundler cache path for TravisCI builds
  .travis.yml
  build_matrix.yml
Labels: chore, dev happiness

#519 Add SUPPORT.md file to link to our support process
  README.md
  SUPPORT.md
Labels: chore

#517 Don't raise error on log file parsing error
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
  spec/support/fixtures/projects/broken/config/appsignal.yml
Labels: bug

#520 Remove class variables
  .rubocop_todo.yml
  lib/appsignal/event_formatter.rb
  lib/appsignal/minutely.rb
  spec/lib/appsignal/minutely_spec.rb
Labels: chore, dev happiness

#522 Test against Rails 6 rc1
  gemfiles/rails-6.0.gemfile
Labels: chore

#523 Add dependency check to probes
  lib/appsignal/hooks/sidekiq.rb
  lib/appsignal/minutely.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
  spec/lib/appsignal/minutely_spec.rb
Labels: enhancement
