Repository appsignal/appsignal-ruby, pull requests merged in 2020-11, with the labels that each got.

#662 Remove unused argument
  ext/appsignal_extension.c
Labels: chore

#664 Revert agent
  ext/agent.yml
Labels: bug

#663 Activesupport instrumentation refactor
  lib/appsignal/hooks/active_support_notifications.rb
  spec/lib/appsignal/hooks/active_support_notifications/finish_with_state_shared_examples.rb
  spec/lib/appsignal/hooks/active_support_notifications/instrument_shared_examples.rb
  spec/lib/appsignal/hooks/active_support_notifications/start_finish_shared_examples.rb
  spec/lib/appsignal/hooks/active_support_notifications_spec.rb
Labels: enhancement
