Repository appsignal/appsignal-ruby, pull requests merged in 2020-02, with the labels that each got.

#585 Add logger that can warn once, then use debug.
  lib/appsignal.rb
  lib/appsignal/logger.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/logger_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/log_helpers.rb
Labels: enhancement

#587 Move test build to Semaphore
  .semaphore/semaphore.yml
  .travis.yml
  README.md
  Rakefile
  build_matrix.yml
  support/install_deps
Labels: dev happiness, enhancement

#590 Fix ruby names for builds
  .semaphore/semaphore.yml
  Rakefile
  build_matrix.yml
Labels: chore, dev happiness

#592 Add check for correct Ruby version
  .semaphore/semaphore.yml
  build_matrix.yml
  support/check_versions
Labels: chore, dev happiness

#593 Remove public_suffix gem from gemfiles
  .semaphore/semaphore.yml
  build_matrix.yml
  gemfiles/capistrano2.gemfile
  gemfiles/capistrano3.gemfile
  gemfiles/grape.gemfile
  gemfiles/no_dependencies.gemfile
  gemfiles/padrino.gemfile
  gemfiles/que.gemfile
  gemfiles/que_beta.gemfile
  gemfiles/rails-3.2.gemfile
  gemfiles/rails-4.0.gemfile
  gemfiles/rails-4.1.gemfile
  gemfiles/rails-4.2.gemfile
  gemfiles/resque.gemfile
Labels: chore, dev happiness

#594 Fix set auto action name with custom action
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: bug, support
