Repository appsignal/appsignal-ruby, pull requests merged in 2020-01, with the labels that each got.

#578 Add tests for Ruby 2.7
  .travis.yml
  build_matrix.yml
  gemfiles/padrino.gemfile
  gemfiles/resque.gemfile
Labels: feature

#579 Update Ruby to 2.6.5 in test matrix
  .travis.yml
  build_matrix.yml
Labels: chore

#577 Update ca-cert.pem to recent version
  resources/cacert.pem
Labels: chore

#580 Remove SSL version lock in transmitter
  lib/appsignal/transmitter.rb
Labels: bug, security

#581 Fix wait_for helper
  spec/support/helpers/wait_for_helper.rb
Labels: bug

#582 Fix exception handling of config file issues
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
  spec/support/fixtures/projects/broken/config/appsignal.yml
Labels: bug
