Repository appsignal/appsignal-ruby, pull requests merged in 2020-06, with the labels that each got.

#609 Fix checksum check failure logging
  ext/base.rb
Labels: bug

#607 Clean bundle in CI jobs
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore, dev happiness

#612 Refactor DelayedJob specs
  lib/appsignal/integrations/delayed_job_plugin.rb
  spec/lib/appsignal/hooks/delayed_job_spec.rb
Labels: chore, dev happiness

#613 Revert DelayedJob class/method name extraction method logic for Class methods
  lib/appsignal/integrations/delayed_job_plugin.rb
  spec/lib/appsignal/hooks/delayed_job_spec.rb
Labels: bug

#611 Fix issue where Delayed Job job objects responding to Hash accessor assumes string return value
  lib/appsignal/integrations/delayed_job_plugin.rb
  spec/lib/appsignal/hooks/delayed_job_spec.rb
Labels: bug

#614 Set bundle clean flag
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore, dev happiness

#606 Use http proxy when bundling if set
  ext/base.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
Labels: enhancement

#615 Fix ResqueActiveJobPlugin specs
  spec/lib/appsignal/integrations/resque_active_job_spec.rb
Labels: bug

#616 Support queueing time metrics for ResqueActiveJob
  lib/appsignal/integrations/resque_active_job.rb
  spec/lib/appsignal/integrations/resque_active_job_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: enhancement

#617 Add helpers for environment metadata collection
  ext/agent.yml
  ext/appsignal_extension.c
  lib/appsignal.rb
  lib/appsignal/environment.rb
  lib/appsignal/extension/jruby.rb
  spec/lib/appsignal/environment_spec.rb
Labels: enhancement

#618 Add environment metadata report method guards
  lib/appsignal/environment.rb
  spec/lib/appsignal/environment_spec.rb
Labels: enhancement

#619 Add send_environment_metadata option
  ext/agent.yml
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: enhancement

#620 Mention disabling enable_frontend_error_catching in JSExceptionCatcher deprecation message
  lib/appsignal/rack/js_exception_catcher.rb
  spec/lib/appsignal/rack/js_exception_catcher_spec.rb
Labels: enhancement

#621 Report Ruby environment metadata
  lib/appsignal.rb
  lib/appsignal/capistrano.rb
  lib/appsignal/environment.rb
  lib/appsignal/hooks/net_http.rb
  lib/appsignal/hooks/redis.rb
  lib/appsignal/hooks/sequel.rb
  lib/appsignal/integrations/object.rb
  lib/appsignal/integrations/resque_active_job.rb
  spec/lib/appsignal/environment_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/environment_metdata_helper.rb
Labels: enhancement

#622 Reduce number of duplicate specs
  spec/lib/appsignal/hooks/sidekiq_spec.rb
Labels: chore, dev happiness
