Repository appsignal/appsignal-ruby, pull requests merged in 2020-07, with the labels that each got.

#623 Move minutely probe to their own file and module
  lib/appsignal/hooks/puma.rb
  lib/appsignal/hooks/sidekiq.rb
  lib/appsignal/probes/puma.rb
  lib/appsignal/probes/sidekiq.rb
  lib/puma/plugin/appsignal.rb
  spec/lib/appsignal/hooks/puma_spec.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
  spec/lib/appsignal/probes/puma_spec.rb
  spec/lib/appsignal/probes/sidekiq_spec.rb
  spec/lib/puma/appsignal_spec.rb
  spec/support/stubs/sidekiq/api.rb
Labels: chore, dev happiness

#624 Bump Ruby 2.7 build to 2.7.1
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#626 Only restore CI caches on exact match
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#625 Bump Padrino build
  .semaphore/semaphore.yml
  build_matrix.yml
  gemfiles/padrino.gemfile
  spec/lib/appsignal/integrations/padrino_spec.rb
Labels: chore

#627 Bump agent to v-710d341
  ext/agent.yml
Labels: chore

#628 Support custom actions in que jobs
  lib/appsignal/integrations/que.rb
  spec/lib/appsignal/integrations/que_spec.rb
Labels: bug

#630 Rework Resque and Resque ActiveJob integrations
  .semaphore/semaphore.yml
  build_matrix.yml
  gemfiles/resque-1.gemfile
  gemfiles/resque-2.gemfile
  lib/appsignal/hooks.rb
  lib/appsignal/hooks/resque.rb
  lib/appsignal/integrations/resque.rb
  lib/appsignal/integrations/resque_active_job.rb
  lib/appsignal/utils/deprecation_message.rb
  spec/lib/appsignal/hooks/resque_spec.rb
  spec/lib/appsignal/integrations/resque_active_job_spec.rb
  spec/lib/appsignal/integrations/resque_spec.rb
Labels: enhancement

#629 Improved ActiveJob support
  .rubocop.yml
  .semaphore/semaphore.yml
  build_matrix.yml
  gemfiles/rails-4.2.gemfile
  gemfiles/rails-5.0.gemfile
  gemfiles/rails-5.1.gemfile
  gemfiles/rails-5.2.gemfile
  gemfiles/rails-6.0.gemfile
  gemfiles/resque-1.gemfile
  gemfiles/resque-2.gemfile
  lib/appsignal/hooks.rb
  lib/appsignal/hooks/active_job.rb
  lib/appsignal/hooks/resque.rb
  lib/appsignal/hooks/sidekiq.rb
  lib/appsignal/integrations/resque.rb
  lib/appsignal/integrations/resque_active_job.rb
  lib/appsignal/transaction.rb
  lib/appsignal/utils/deprecation_message.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
  spec/lib/appsignal/hooks/resque_spec.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
  spec/lib/appsignal/integrations/resque_active_job_spec.rb
  spec/lib/appsignal/integrations/resque_spec.rb
  spec/lib/appsignal/probes/sidekiq_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/support/helpers/action_mailer_helpers.rb
  spec/support/helpers/dependency_helper.rb
  spec/support/helpers/transaction_helpers.rb
  spec/support/stubs/sidekiq/api.rb
Labels: feature

#631 Bump agent to v-a5b5db2
  ext/agent.yml
Labels: enhancement

#632 Add support for Active Job priority
  lib/appsignal/hooks/active_job.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
Labels: enhancement

#633 Track Active Job job metrics
  lib/appsignal/hooks/active_job.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
Labels: feature

#634 Bump agent to v-4548c88
  ext/agent.yml
Labels: bug

#636 Fix diagnose installation result display
  lib/appsignal/cli/diagnose.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
Labels: bug

#640 Use Sidekiq jid as transaction ID
  lib/appsignal/hooks/sidekiq.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
Labels: enhancement

#639 Always report Active Job ID
  lib/appsignal/hooks/active_job.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
Labels: enhancement

#642 Support Delayed::Job jobs without method name
  lib/appsignal/integrations/delayed_job_plugin.rb
  spec/lib/appsignal/hooks/delayed_job_spec.rb
Labels: bug

#643 Report Active Job metrics per queue and with prio
  lib/appsignal/hooks/active_job.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
Labels: enhancement

#644 Support old probe constant names
  lib/appsignal.rb
  lib/appsignal/hooks.rb
  lib/appsignal/hooks/puma.rb
  lib/appsignal/hooks/sidekiq.rb
  lib/appsignal/probes.rb
  lib/appsignal/probes/puma.rb
  lib/appsignal/probes/sidekiq.rb
  spec/lib/appsignal/hooks_spec.rb
Labels: bug

#638 Support setting a specific configuration file
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
  spec/support/helpers/config_helpers.rb
Labels: enhancement

#647 Use extend instead of method aliasing for testing
  spec/support/testing.rb
Labels: chore, dev happiness

#648 Print warnings using Kernel.warn
  lib/appsignal/config.rb
  lib/appsignal/utils/deprecation_message.rb
Labels: enhancement

#650 Remove JRuby spec if statement
  spec/lib/appsignal/extension/jruby_spec.rb
  spec/spec_helper.rb
Labels: chore, dev happiness

#649 Update deprecation message to use helper
  lib/appsignal/auth_check.rb
  spec/lib/appsignal/auth_check_spec.rb
Labels: chore

#651 Print error of AppSignal extension not loaded
  .semaphore/semaphore.yml
  Rakefile
  ext/Rakefile
  ext/base.rb
  ext/extconf.rb
  lib/appsignal/extension.rb
  lib/appsignal/extension/jruby.rb
  spec/lib/appsignal/extension_install_failure_spec.rb
  spec/spec_helper.rb
  spec/support/testing.rb
Labels: enhancement

#652 Bump agent to v-c8f8185
  ext/agent.yml
Labels: bug

#653 Fix configuration for working_directory_path
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: bug

#654 Ensure config env keys are configured
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: bug
