Repository appsignal/appsignal-ruby, pull requests merged in 2021-03, with the labels that each got.

#708 Spans API
  ext/appsignal_extension.c
  lib/appsignal/config.rb
  lib/appsignal/extension.rb
  lib/appsignal/extension/jruby.rb
  lib/appsignal/span.rb
  lib/appsignal/utils/data.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/span_spec.rb
Labels: enhancement

#709 DNS config is an array
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: bug

#711 Remove middleware insert for JS middleware
  lib/appsignal/integrations/railtie.rb
Labels: bug

#712 Fix deprecation message for set_error namespace
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#713 Fix example code for Transaction#set_namespace
  lib/appsignal/transaction.rb
Labels: chore
