Repository appsignal/appsignal-ruby, pull requests merged in 2021-02, with the labels that each got.

#698 Prepend Sidekiq middleware
  lib/appsignal/hooks/sidekiq.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
Labels: enhancement

#700 Bump Ruby versions to latest patch releases
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#701 Require Ruby 2.0 for gem
  appsignal.gemspec
Labels: chore

#699 Add Sidekiq error handler
  .rubocop_todo.yml
  lib/appsignal/hooks.rb
  lib/appsignal/hooks/sidekiq.rb
  lib/appsignal/integrations/sidekiq.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
  spec/lib/appsignal/hooks_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
Labels: enhancement

#702 Deprecate error helpers tags and namespace arguments
  lib/appsignal.rb
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#705 Fix ActionCable integration in test environment
  lib/appsignal/hooks/action_cable.rb
  spec/lib/appsignal/hooks/action_cable_spec.rb
Labels: bug

#704 Mark minutely probe thread as fork-safe
  lib/appsignal/minutely.rb
  spec/lib/puma/appsignal_spec.rb
Labels: enhancement

#706 Update method delegation in method instrumentation
  lib/appsignal/integrations/object_ruby_modern.rb
  spec/lib/appsignal/integrations/object_spec.rb
Labels: bug
