Repository appsignal/appsignal-ruby, pull requests merged in 2021-01, with the labels that each got.

#666 Add breadcrumbs as sample data
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/hooks/resque_spec.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#680 Fix Ruby 1.9 build
  gemfiles/no_dependencies.gemfile
Labels: bug

#679 Log Ruby errors on extension download
  ext/base.rb
Labels: chore

#681 Support Ruby 3.0
  .semaphore/semaphore.yml
  build_matrix.yml
  ext/base.rb
  gemfiles/resque-2.gemfile
  gemfiles/webmachine.gemfile
  lib/appsignal/cli/diagnose/utils.rb
  lib/appsignal/cli/install.rb
Labels: feature

#683 Drop Ruby 1.9, switch to using Module.prepend instead of method aliasing
  .semaphore/semaphore.yml
  build_matrix.yml
  lib/appsignal/hooks/action_cable.rb
  lib/appsignal/hooks/active_support_notifications.rb
  lib/appsignal/hooks/celluloid.rb
  lib/appsignal/hooks/net_http.rb
  lib/appsignal/hooks/puma.rb
  lib/appsignal/hooks/que.rb
  lib/appsignal/hooks/rake.rb
  lib/appsignal/hooks/redis.rb
  lib/appsignal/hooks/resque.rb
  lib/appsignal/hooks/unicorn.rb
  lib/appsignal/hooks/webmachine.rb
  lib/appsignal/integrations/action_cable.rb
  lib/appsignal/integrations/active_support_notifications.rb
  lib/appsignal/integrations/net_http.rb
  lib/appsignal/integrations/padrino.rb
  lib/appsignal/integrations/que.rb
  lib/appsignal/integrations/rake.rb
  lib/appsignal/integrations/redis.rb
  lib/appsignal/integrations/resque.rb
  lib/appsignal/integrations/unicorn.rb
  lib/appsignal/integrations/webmachine.rb
  spec/lib/appsignal/hooks/celluloid_spec.rb
  spec/lib/appsignal/hooks/rake_spec.rb
  spec/lib/appsignal/hooks/redis_spec.rb
  spec/lib/appsignal/hooks/unicorn_spec.rb
  spec/lib/appsignal/hooks/webmachine_spec.rb
  spec/lib/appsignal/integrations/padrino_spec.rb
  spec/lib/appsignal/integrations/webmachine_spec.rb
Labels: chore

#682 Bump RuboCop to TargetRubyVersion 2.0
  .rubocop.yml
  spec/spec_helper.rb
Labels: chore

#685 Remove deprecated methods for gem version 3.0
  lib/appsignal.rb
  lib/appsignal/auth_check.rb
  lib/appsignal/cli.rb
  lib/appsignal/cli/notify_of_deploy.rb
  lib/appsignal/config.rb
  lib/appsignal/event_formatter.rb
  lib/appsignal/integrations/resque.rb
  lib/appsignal/integrations/resque_active_job.rb
  spec/lib/appsignal/auth_check_spec.rb
  spec/lib/appsignal/cli/notify_of_deploy_spec.rb
  spec/lib/appsignal/cli_spec.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/event_formatter_spec.rb
  spec/lib/appsignal/integrations/resque_active_job_spec.rb
  spec/lib/appsignal/integrations/resque_spec.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#689 Remove ruby-build pull exception
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#688 Remove Ruby 1.9 specific spec and helpers
  spec/lib/appsignal/auth_check_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal/transmitter_spec.rb
  spec/spec_helper.rb
Labels: chore

#691 Remove rbenv gem-rehash plugin
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#687 Support batched Shoryuken workers
  lib/appsignal/hooks/shoryuken.rb
  spec/lib/appsignal/hooks/shoryuken_spec.rb
Labels: bug

#686 Remove more deprecations for 3.0
  lib/appsignal.rb
  lib/appsignal/config.rb
  lib/appsignal/hooks.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/js_exception_transaction.rb
  lib/appsignal/minutely.rb
  lib/appsignal/rack/js_exception_catcher.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/hooks_spec.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
  spec/lib/appsignal/js_exception_transaction_spec.rb
  spec/lib/appsignal/minutely_spec.rb
  spec/lib/appsignal/rack/js_exception_catcher_spec.rb
Labels: chore

#694 Remove Ruby 1.9 support for method instrumentation
  lib/appsignal/integrations/object.rb
  lib/appsignal/integrations/object_ruby_19.rb
  lib/appsignal/integrations/object_ruby_modern.rb
  spec/lib/appsignal/integrations/object_19_spec.rb
  spec/lib/appsignal/integrations/object_spec.rb
Labels: chore
