Repository appsignal/appsignal-ruby, pull requests merged in 2022-08, with the labels that each got.

#869 Change `gauge_delta` so it expects a block
  lib/appsignal/probes/helpers.rb
  lib/appsignal/probes/mri.rb
  lib/appsignal/probes/sidekiq.rb
Labels: chore

#870 Lock webmock version for older Rubies
  appsignal.gemspec
Labels: chore

#871 Add Transaction.current? helper
  .changesets/add-transaction-current?-helper.md
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/hooks/active_job.rb
  lib/appsignal/integrations/mongo_ruby_driver.rb
  lib/appsignal/integrations/sidekiq.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/transaction_helpers.rb
Labels: enhancement

#872 Rewrite Rails middleware specs to use to_json
  spec/lib/appsignal/rack/rails_instrumentation_spec.rb
  spec/support/helpers/env_helpers.rb
  spec/support/testing.rb
Labels: chore, dev happiness

#873 Fix Rails error on unknown request method
  .changesets/fix-error-on-unknown-http-request-method.md
  lib/appsignal/rack/rails_instrumentation.rb
  spec/lib/appsignal/rack/rails_instrumentation_spec.rb
Labels: bug

#874 Rename gc_total_time to gc_time
  .changesets/rename-gc_total_time-metric-to-gc_time.md
  lib/appsignal/probes/mri.rb
  spec/lib/appsignal/probes/mri_spec.rb
Labels: chore

#875 Refactor internal Garbage Collection behavior
  .changesets/fix-garbage-collection-profiler.md
  lib/appsignal.rb
  lib/appsignal/garbage_collection.rb
  lib/appsignal/garbage_collection_profiler.rb
  lib/appsignal/probes/mri.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/garbage_collection_spec.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: chore

#877 Only report gc_time metric if profiler is enabled
  .changesets/support-temporarily-disabling-gc-profiling.md
  lib/appsignal/probes/mri.rb
  spec/lib/appsignal/probes/mri_spec.rb
Labels: enhancement

#876 Remove GC::Profiler.enable
  lib/appsignal.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#879 Enable GC profiling when it's enabled in an app
  .changesets/listen-if-garbage-collection-is-enabled.md
  lib/appsignal/garbage_collection.rb
  lib/appsignal/probes/mri.rb
  spec/lib/appsignal/garbage_collection_spec.rb
  spec/lib/appsignal/probes/mri_spec.rb
Labels: enhancement
