Repository appsignal/appsignal-ruby, pull requests merged in 2022-07, with the labels that each got.

#852 MRI VM Stats
  .changesets/add-a-mri-vm-probe-to-add-a-magic-dashboard.md
  .semaphore/semaphore.yml
  build_matrix.yml
  gemfiles/grape.gemfile
  lib/appsignal/probes/mri.rb
  spec/lib/appsignal/probes/mri_spec.rb
Labels: feature

#856 Fix appsignal_free_* FFI missing pointer arguments
  .changesets/fix-ffi-arguments-for-free-functions.md
  lib/appsignal/extension/jruby.rb
Labels: bug

#861 Bump Lintje 0.7.1
  script/lint_git
Labels: chore, dev happiness

#862 Add JRuby 9.3 build to CI
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#863 Store delta gauge of allocated objects in Ruby
  .changesets/report-gauge-delta-value-for-allocated-objects.md
  lib/appsignal/probes.rb
  lib/appsignal/probes/helpers.rb
  lib/appsignal/probes/mri.rb
  lib/appsignal/probes/sidekiq.rb
  spec/lib/appsignal/probes/mri_spec.rb
Labels: enhancement

#865 Store delta gauge of Garbage Collection counts
  .changesets/report-gauge-delta-value-for-gc_count.md
  lib/appsignal/probes/mri.rb
  spec/lib/appsignal/probes/mri_spec.rb
Labels: enhancement

#866 Report Ruby VM probe metrics as gauges with a hostname tag
  .changesets/report-all-ruby-vm-metrics-as-gauges.md
  .changesets/track-hostname-tag-for-ruby-vm-metrics.md
  lib/appsignal/probes/mri.rb
  spec/lib/appsignal/probes/mri_spec.rb
  spec/support/helpers/config_helpers.rb
Labels: bug

#864 Bump agent to 06391fb
  .changesets/bump-agent-06391fb.md
  ext/agent.yml
Labels: enhancement

#867 Store delta gauge of Garbage Collection total time
  .changesets/report-delta-gc-total-time-metric.md
  lib/appsignal/probes/mri.rb
  spec/lib/appsignal/probes/mri_spec.rb
Labels: bug
