Repository appsignal/appsignal-ruby, pull requests merged in 2022-02, with the labels that each got.

#816 Fix RSpec mock expectations for Ruby 3
  spec/lib/appsignal/event_formatter/mongo_ruby_driver/query_formatter_spec.rb
  spec/lib/appsignal/integrations/mongo_ruby_driver_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/transaction_helpers.rb
Labels: chore

#818 Remove the private and internal extension system
  .changesets/remove-internal-extensions-system.md
  lib/appsignal.rb
  spec/lib/appsignal_spec.rb
  spec/support/mocks/mock_extension.rb
Labels: chore

#819 Improve MongoDB query sanitization
  CHANGELOG.md
  lib/appsignal/event_formatter/mongo_ruby_driver/query_formatter.rb
  lib/appsignal/version.rb
  spec/lib/appsignal/event_formatter/mongo_ruby_driver/query_formatter_spec.rb
  spec/lib/appsignal/utils/query_params_sanitizer_spec.rb
Labels: enhancement, support

#824 Fix Padrino tests for new Sinatra version
  spec/lib/appsignal/integrations/padrino_spec.rb
Labels: chore

#828 Bump agent to v-bbc830a
  .changesets/bump-agent-to-v-bbc830a.md
  ext/agent.yml
Labels: chore

#825 Fix Array type wrapper in QueryParamsSanitizer
  .changesets/fix-wrapper-array-around-sanitized-values.md
  lib/appsignal/utils/query_params_sanitizer.rb
  spec/lib/appsignal/event_formatter/moped/query_formatter_spec.rb
  spec/lib/appsignal/utils/query_params_sanitizer_spec.rb
Labels: bug

#829 Fix load order issue with ActiveJob default queue
  .changesets/fix-activejob-default_queue_name-issue-being-reset-to--default-.md
  lib/appsignal/hooks/active_job.rb
Labels: bug

#831 Bump minimal Rake version to version 12
  appsignal.gemspec
Labels: chore

#832 Bump agent to v-f57e6cb
  .changesets/bump-agent-to-v-f57e6cb.md
  ext/agent.yml
Labels: enhancement
