Repository appsignal/appsignal-ruby, pull requests merged in 2023-07, with the labels that each got.

#976 Ignore recursively nested values on sanitize
  .changesets/ignore-recursively-nested-values-on-sanitize.md
  lib/appsignal/utils/hash_sanitizer.rb
  spec/lib/appsignal/utils/hash_sanitizer_spec.rb
Labels: bug

#979 Remove agent install artifact from history
  .gitignore
  ext/._appsignal-agent
Labels: chore

#981 Bump agent to 32590eb
  .changesets/bump-agent-to-32590eb.md
  ext/agent.rb
Labels: enhancement

#980 Add bind_address config option for the agent
  .changesets/allow-bind_address-configuration.md
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: enhancement

#982 Report total CPU usage host metric for VMs
  .changesets/report-total-cpu-usage-metric-for-vms.md
  ext/agent.rb
Labels: enhancement

#983 Send array and hash tags as custom_data
  .changesets/send-custom-data-via-rails-error-reporter.md
  lib/appsignal/integrations/railtie.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
Labels: enhancement
