Repository appsignal/appsignal-ruby, pull requests merged in 2023-03, with the labels that each got.

#923 Load RACK_ENV or RAILS_ENV in diagnose report
  .changesets/load-rails_env-in-diagnose-cli.md
  lib/appsignal/cli/diagnose.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/support/fixtures/projects/valid/config/appsignal.yml
Labels: enhancement

#929 support "warning" alias for WARN log level
  .changesets/support-warning-log_level.md
  lib/appsignal/config.rb
Labels: bug

#933 Fix default Ruby logger formatter usage
  .changesets/fix-default-ruby-logger-formatter-usage.md
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: bug, support

#934 Add webmachine version 2 to build matrix
  .semaphore/semaphore.yml
  build_matrix.yml
  gemfiles/webmachine1.gemfile
  gemfiles/webmachine2.gemfile
Labels: chore

#935 Fix ActiveSupport Logger broadcast usage
  .changesets/fix-activesupport-logger-broadcast.md
  lib/appsignal/logger.rb
Labels: bug
