Repository appsignal/appsignal-ruby, pull requests merged in 2023-12, with the labels that each got.

#1010 Add error causes tree as transaction metadata
  .changesets/store-error-causes-as-transaction-sample-data.md
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: enhancement, feature, requests

#1016 Fix diagnose file read error on illegal seeks
  .changesets/fix-error-in-diagnose-report-path-read.md
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/cli/diagnose/paths.rb
  spec/lib/appsignal/cli/diagnose/utils_spec.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
Labels: bug

#1019 Fix for Ruby 3.3
  .changesets/fix-compatibility-for-ruby-3-3.md
  lib/appsignal/logger.rb
Labels: bug, support

#1020 Fix compatibility for Ruby Logger 1.6.0
  .changesets/fix-ruby-logger-1-6-0-compatibility.md
  lib/appsignal/logger.rb
Labels: bug, support
