Repository appsignal/appsignal-ruby, pull requests merged in 2023-06, with the labels that each got.

#968 Add statsd_port config option
  .changesets/bump-agent-to-fd8ee9e.md
  .changesets/statsd-port-config-option.md
  ext/agent.rb
  lib/appsignal/config.rb
  lib/puma/plugin/appsignal.rb
  spec/lib/appsignal/config_spec.rb
Labels: enhancement

#969 Fix ActiveSupport Logger broadcast compatibility
  .changesets/fix-activesupport-logger-broadcast-compatibility.md
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: bug

#971 Refactor Sinatra spec to Transaction#to_h usage + bug fix
  .changesets/fix-sinatra-request-custom-params-method.md
  lib/appsignal/rack/sinatra_instrumentation.rb
  spec/lib/appsignal/rack/sinatra_instrumentation_spec.rb
Labels: bug, chore

#974 Fix issue with invalid breadcrumb metadata
  .changesets/check-argument-type-of-breadcrumb-metadata.md
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: bug
