Repository appsignal/appsignal-ruby, pull requests merged in 2023-11, with the labels that each got.

#1007 Fix error in Sidekiq probe on missing Redis info
  .changesets/fix-internal-error-on-missing-redis-info.md
  lib/appsignal/probes/sidekiq.rb
  spec/lib/appsignal/probes/sidekiq_spec.rb
Labels: bug

#1008 Bump agent to 1dd2a18
  .changesets/bump-agent-1dd2a18.md
  ext/agent.rb
Labels: enhancement

#1011 Bump agent to eec7f7b
  .changesets/cgroups-v2-cpu-stats-normalization.md
  ext/agent.rb
Labels: chore

#1014 Bump agent to aa4daed
  .changesets/probes-update.md
  .changesets/skip-more-disk-mountpoints.md
  ext/agent.rb
Labels: chore
