Repository appsignal/appsignal-ruby, pull requests merged in 2023-04, with the labels that each got.

#939 Remove EOL libraries and versions from CI
  .changesets/remove-support-for-versions-in-eol.md
  .rubocop_todo.yml
  .semaphore/semaphore.yml
  Gemfile
  appsignal.gemspec
  build_matrix.yml
  gemfiles/rails-3.2.gemfile
  gemfiles/rails-4.2.gemfile
  gemfiles/rails-5.0.gemfile
  gemfiles/rails-5.1.gemfile
  gemfiles/rails-5.2.gemfile
  gemfiles/resque-1.gemfile
  gemfiles/sequel-435.gemfile
Labels: chore, dev happiness

#940 Upgrade Rubocop version and fix offenses
  .rubocop.yml
  Rakefile
  bin/appsignal
  ext/Rakefile
  lib/appsignal/integrations/capistrano/appsignal.cap
Labels: chore, dev happiness

#942 Upgrade Lintje 0.11.3
  script/lint_git
Labels: chore

#945 Extract Active Job metadata earlier
  .changesets/set-appsignal-transaction-namespace--action-name-and-some-tags-earlier-.md
  lib/appsignal/hooks/active_job.rb
Labels: enhancement

#949 Remove ruby v2 version checks
  .changesets/remove-ruby-2-version-checks.md
  lib/appsignal/cli/helpers.rb
  lib/appsignal/cli/install.rb
  spec/lib/appsignal/probes/mri_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: chore

#956 Bump JRuby to 9.4.1.0 in CI
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#957 Exclude diagnose path from normal RSpec tests
  spec/spec_helper.rb
Labels: dev happiness

#947 Report GVL global timer metrics if disabled
  lib/appsignal/probes/gvl.rb
  spec/lib/appsignal/probes/gvl_spec.rb
  spec/support/mocks/fake_gvl_tools.rb
Labels: chore

#951 Fix ActiveSupport::TaggedLogging silence usage
  .changesets/fix-a-bug-when-using-activesupport--taggedlogging.md
  ext/._appsignal-agent
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: bug

#958 Disable RuboCop Style/NumericPredicate
  .rubocop.yml
  lib/appsignal/extension/jruby.rb
  lib/appsignal/probes/mri.rb
Labels: chore

#955 Rails error reporter Sidekiq action and namespace
  .changesets/support-sidekiq-in-rails-error-reporter.md
  lib/appsignal/hooks/active_job.rb
  lib/appsignal/integrations/sidekiq.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#961 Update agent to version 6f29190
  .changesets/update-agent-6f29190.md
  ext/agent.rb
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: enhancement
