Repository appsignal/appsignal-ruby, pull requests merged in 2023-02, with the labels that each got.

#917 Undefine allocation function for C extension class
  .changesets/fix-t_data-warning-on-ruby-3-2.md
  ext/appsignal_extension.c
Labels: bug

#919 Bump agent to 0d593d5
  .changesets/bump-agent-to-0d593d5.md
  ext/agent.rb
Labels: enhancement

#920 Bump Ruby versions to the latest patch releases
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#921 Support formats in logger
  .changesets/bump-agent-to-8d042e2.md
  ext/agent.rb
  ext/appsignal_extension.c
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: enhancement
