Repository appsignal/appsignal-ruby, pull requests merged in 2024-04, with the labels that each got.

#1058 Check redis-client gem version to prevent error
  .changesets/check-redis-client-version.md
  lib/appsignal/hooks/redis_client.rb
  spec/lib/appsignal/hooks/redis_client_spec.rb
Labels: bug

#1057 Implement heartbeats for Ruby
  .changesets/add-heartbeats-support.md
  lib/appsignal.rb
  lib/appsignal/heartbeat.rb
  spec/lib/appsignal/heartbeat_spec.rb
Labels: feature

#1062 Test against Ruby 3.3.1
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#1063 Rename module to StdoutAndLoggerMessage
  lib/appsignal.rb
  lib/appsignal/config.rb
  lib/appsignal/event_formatter.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/helpers/metrics.rb
  lib/appsignal/hooks.rb
  lib/appsignal/utils.rb
  lib/appsignal/utils/deprecation_message.rb
  lib/appsignal/utils/stdout_and_logger_message.rb
Labels: chore

#1060 Clear in memory log on logger start
  .changesets/clear-in-memory-log-after-logger-start.md
  lib/appsignal.rb
  spec/lib/appsignal_spec.rb
Labels: bug

#1064 Log log_file_path warning only once
  .changesets/print-log-path-warning-only-once.md
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: enhancement

#1065 Rename Minutely to Probes module
  .changesets/rename-minutely-constant-to-probes.md
  lib/appsignal.rb
  lib/appsignal/hooks/gvl.rb
  lib/appsignal/hooks/mri.rb
  lib/appsignal/hooks/sidekiq.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/minutely.rb
  lib/appsignal/probes.rb
  spec/lib/appsignal/hooks/gvl_spec.rb
  spec/lib/appsignal/hooks/mri_spec.rb
  spec/lib/appsignal/hooks/puma_spec.rb
  spec/lib/appsignal/probes_spec.rb
  spec/lib/appsignal_spec.rb
  spec/spec_helper.rb
Labels: chore

#1067 Start probes registered after thread is started
  .changesets/add-probes-register-method.md
  .changesets/automatically-start-new-probes-on-register.md
  lib/appsignal/probes.rb
  spec/lib/appsignal/probes_spec.rb
Labels: enhancement

#1069 Stop minutely probes thread on Appsignal.stop
  .changesets/stop-minutely-probes-on-appsignal-stop.md
  lib/appsignal.rb
  lib/appsignal/probes.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1066 Listen to APPSIGNAL_HTTP_PROXY in installer
  .changesets/listen-to-appsignal_http_proxy-in-extension-installer.md
  ext/base.rb
Labels: enhancement

#1070 Use different StatsD port during testing
  spec/lib/puma/appsignal_spec.rb
Labels: chore

#1071 Allow probes to be unregistered
  .changesets/unregister-probes.md
  lib/appsignal/probes.rb
  spec/lib/appsignal/probes_spec.rb
Labels: enhancement

#1072 Bump agent to version 0.35.5
  .changesets/log-debug-messages-for-metrics.md
  ext/agent.rb
Labels: chore

#1073 Fix StatsD server port for test server in spec
  spec/lib/puma/appsignal_spec.rb
Labels: chore
