Repository appsignal/appsignal-ruby, pull requests merged in 2024-01, with the labels that each got.

#1023 Remove deprecated extension functions
  .changesets/deprecate-set_host_guage-and-set_process_gauge-helper-methods.md
  ext/appsignal_extension.c
  lib/appsignal/extension/jruby.rb
  lib/appsignal/helpers/metrics.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1025 Bump agent to bfe19b1
  .changesets/remove-deprecated-extension-functions.md
  .changesets/update-probes-0.5.4.md
  ext/agent.rb
Labels: enhancement

#1026 Always print the install.report on CI
  .semaphore/semaphore.yml
  Rakefile
  build_matrix.yml
Labels: chore

#1027 Fix Ruby and JRuby versions in install report
  .changesets/track-ruby-and-jruby-versions-in-install-report-better.md
  ext/Rakefile
  ext/base.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
Labels: bug

#1030 Update Semaphore CI to Ubuntu 20.04
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#1032 Remove unused C version selector on CI
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#1031 Test extension during JRuby install
  .changesets/jruby-extension-installation-test.md
  ext/Rakefile
  lib/appsignal/extension/jruby.rb
Labels: bug

#1028 Add redis-client support
  .changesets/add-redis-client-support.md
  .semaphore/semaphore.yml
  README.md
  build_matrix.yml
  gemfiles/redis-4.gemfile
  gemfiles/redis-5.gemfile
  lib/appsignal/hooks.rb
  lib/appsignal/hooks/redis.rb
  lib/appsignal/hooks/redis_client.rb
  lib/appsignal/integrations/redis_client.rb
  spec/lib/appsignal/hooks/redis_client_spec.rb
  spec/lib/appsignal/hooks/redis_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: feature

#1035 Rename the internal logger method
  lib/appsignal.rb
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/config.rb
  lib/appsignal/environment.rb
  lib/appsignal/event_formatter.rb
  lib/appsignal/extension.rb
  lib/appsignal/extension/jruby.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/helpers/metrics.rb
  lib/appsignal/hooks.rb
  lib/appsignal/integrations/hanami.rb
  lib/appsignal/integrations/padrino.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/integrations/sidekiq.rb
  lib/appsignal/integrations/sinatra.rb
  lib/appsignal/minutely.rb
  lib/appsignal/probes/gvl.rb
  lib/appsignal/probes/helpers.rb
  lib/appsignal/probes/mri.rb
  lib/appsignal/probes/sidekiq.rb
  lib/appsignal/rack/generic_instrumentation.rb
  lib/appsignal/rack/rails_instrumentation.rb
  lib/appsignal/rack/sinatra_instrumentation.rb
  lib/appsignal/rack/streaming_listener.rb
  lib/appsignal/span.rb
  lib/appsignal/transaction.rb
  lib/appsignal/utils/deprecation_message.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
  spec/lib/appsignal/hooks_spec.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
  spec/lib/appsignal/integrations/sinatra_spec.rb
  spec/lib/appsignal/minutely_spec.rb
  spec/lib/appsignal/rack/rails_instrumentation_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
  spec/spec_helper.rb
  spec/support/helpers/config_helpers.rb
  spec/support/helpers/log_helpers.rb
Labels: chore

#1036 Update supported gems in environment metadata
  lib/appsignal/environment.rb
Labels: chore
