Repository appsignal/appsignal-ruby, pull requests merged in 2024-09, with the labels that each got.

#1274 Log a warning for loader defaults after configure
  .changesets/log-warning-for-loader-defaults.md
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: enhancement

#1272 Fix error log message from at_exit without error
  .changesets/fix-error-about-reporting-no-error-on-process-exit-.md
  lib/appsignal/hooks/at_exit.rb
  spec/lib/appsignal/hooks/at_exit_spec.rb
Labels: bug

#1276 Clean up probes spec
  spec/lib/appsignal/probes_spec.rb
  spec/spec_helper.rb
Labels: chore

#1275 Rename the path and method transaction metadata
  .changesets/rename-path-and-method-transaction-metadata.md
  lib/appsignal/rack.rb
  spec/lib/appsignal/integrations/puma_spec.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
Labels: enhancement

#1270 Report low-level Puma errors
  .changesets/drop-support-for-puma-2-and-lower.md
  .changesets/rename-path-and-method-transaction-metadata.md
  .changesets/report-puma-low-level-errors.md
  lib/appsignal/hooks/puma.rb
  lib/appsignal/integrations/puma.rb
  lib/appsignal/rack.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/event_handler.rb
  lib/appsignal/rack/hanami_middleware.rb
  spec/lib/appsignal/hooks/puma_spec.rb
  spec/lib/appsignal/integrations/puma_spec.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
  spec/lib/appsignal/rack_spec.rb
  spec/support/mocks/hash_like.rb
  spec/support/mocks/puma_mock.rb
Labels: enhancement

#1278 Bump agent to version 0.35.22
  .changesets/internal-change-to-how-opentelemetry-metrics-are-sent.md
  ext/agent.rb
Labels: chore

#1279 Add dummy logs to probes spec to debug spec issue
  spec/lib/appsignal/probes_spec.rb
Labels: chore

#1281 Support Que 2 keyword arguments
  .changesets/add-support-for-que-2-keyword-arguments.md
  .github/workflows/ci.yml
  build_matrix.yml
  gemfiles/que-1.gemfile
  gemfiles/que-2.gemfile
  gemfiles/que.gemfile
  lib/appsignal/integrations/que.rb
  spec/lib/appsignal/integrations/que_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: enhancement

#1280 Refactor Check-In request specs
  lib/appsignal/check_in/scheduler.rb
  spec/lib/appsignal/check_in/cron_spec.rb
  spec/lib/appsignal/check_in/scheduler_spec.rb
  spec/spec_helper.rb
  spec/support/helpers/api_request_helper.rb
  spec/support/testing.rb
Labels: chore

#1282 Refactor tests for private methods
  spec/lib/appsignal/transaction_spec.rb
Labels: chore

#1283 Bump agent to version 0.35.23
  .changesets/internal-opentelemetry-change.md
  ext/agent.rb
Labels: chore

#1284 Try a port range for StatsD specs
  spec/lib/puma/appsignal_spec.rb
Labels: chore

#1285 Stub constants in specs
  spec/lib/appsignal/cli/install_spec.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
  spec/lib/appsignal/hooks/celluloid_spec.rb
  spec/lib/appsignal/hooks/data_mapper_spec.rb
  spec/lib/appsignal/hooks/delayed_job_spec.rb
  spec/lib/appsignal/hooks/excon_spec.rb
  spec/lib/appsignal/hooks/gvl_spec.rb
  spec/lib/appsignal/hooks/mongo_ruby_driver_spec.rb
  spec/lib/appsignal/hooks/passenger_spec.rb
  spec/lib/appsignal/hooks/shoryuken_spec.rb
  spec/lib/appsignal/hooks/unicorn_spec.rb
  spec/lib/appsignal/integrations/data_mapper_spec.rb
  spec/lib/appsignal/integrations/delayed_job_plugin_spec.rb
  spec/lib/appsignal/integrations/object_spec.rb
  spec/lib/appsignal/integrations/resque_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
  spec/lib/appsignal/rack/grape_middleware_spec.rb
  spec/lib/appsignal_spec.rb
  spec/lib/puma/appsignal_spec.rb
Labels: chore

#1286 Stub constants in specs
  spec/lib/appsignal/integrations/delayed_job_plugin_spec.rb
Labels: chore

#1287 Bump agent to version 0.35.24
  .changesets/fix-internal-opentelemetry-metric-value-conversion.md
  ext/agent.rb
Labels: chore

#1288 Bump agent to version 0.35.25
  .changesets/fix-opentelemetry-metrics-timestamp-key.md
  ext/agent.rb
Labels: chore

#1289 Fix API docs issues
  lib/appsignal/check_in.rb
  lib/appsignal/config.rb
Labels: chore

#1292 Refactor Resque parameters storage
  lib/appsignal/integrations/resque.rb
Labels: chore

#1290 Reduce gem package size by not including development files
  .changesets/do-not-publish-support-files.md
  .github/workflows/ci.yml
  Rakefile
  appsignal.gemspec
  script/bundler_wrapper
  script/install_deps
Labels: enhancement

#1291 Format Date and Time objects stored in sample data
  .changesets/format-date-and-time-objects-in-a-human-friendly-way.md
  lib/appsignal/utils/hash_sanitizer.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal/utils/hash_sanitizer_spec.rb
Labels: enhancement

#1296 Add logger gem as a dependency
  .changesets/add-logger-as-dependency.md
  appsignal.gemspec
Labels: chore

#1297 Fix the RuboCop paths in the gemspec to ignore
  appsignal.gemspec
Labels: chore

#1298 Refactor Data specs
  lib/appsignal/utils/data.rb
  spec/lib/appsignal/utils/data_spec.rb
Labels: dev happiness

#1294 Ignore Errno::EPIPE error causes when reading body (Puma)
  .changesets/do-not-report-puma--connectionerror-when-instrumenting-response-bodies.md
  lib/appsignal/rack/body_wrapper.rb
  spec/lib/appsignal/rack/body_wrapper_spec.rb
Labels: bug

#1299 Refactor sample data sanitizer specs
  lib/appsignal/transaction.rb
  lib/appsignal/utils.rb
  lib/appsignal/utils/sample_data_sanitizer.rb
  spec/lib/appsignal/utils/hash_sanitizer_spec.rb
  spec/lib/appsignal/utils/sample_data_sanitizer_spec.rb
Labels: dev happiness

#1300 Normalize UploadedFile objects in sample data
  .changesets/normalize-uploadedfile-objects.md
  lib/appsignal/utils/sample_data_sanitizer.rb
  spec/lib/appsignal/utils/sample_data_sanitizer_spec.rb
  spec/support/fixtures/uploaded_file.txt
  spec/support/helpers/transaction_helpers.rb
Labels: enhancement

#1302 Add agent release workflow
  .github/workflows/agent_release.yml
Labels: chore

#1303 Remove backtrace cleaner filter after test
  spec/lib/appsignal/transaction_spec.rb
Labels: chore

#1293 Implement heartbeat checkins
  .changesets/add-heartbeat-check-ins.md
  lib/appsignal/check_in.rb
  lib/appsignal/check_in/cron.rb
  lib/appsignal/check_in/event.rb
  lib/appsignal/check_in/scheduler.rb
  spec/lib/appsignal/check_in/cron_spec.rb
  spec/lib/appsignal/check_in/event_spec.rb
  spec/lib/appsignal/check_in/heartbeat_spec.rb
  spec/lib/appsignal/check_in/scheduler_spec.rb
  spec/support/helpers/api_request_helper.rb
Labels: feature

#1304 Add first backtrace line to error causes
  .changesets/include-first-backtrace-line-from-error-causes.md
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/support/helpers/config_helpers.rb
Labels: enhancement

#1305 Refactor specs
  spec/lib/appsignal/check_in/cron_spec.rb
  spec/lib/appsignal/transmitter_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/config_helpers.rb
Labels: chore

#1306 Fix internal logger in Capistrano tasks and remove Config logger instance
  .changesets/fix-no-logs-appearing-from-capistrano-tasks.md
  lib/appsignal.rb
  lib/appsignal/config.rb
  lib/appsignal/integrations/capistrano/appsignal.cap
  lib/appsignal/integrations/capistrano/capistrano_2_tasks.rb
  lib/appsignal/transmitter.rb
  spec/lib/appsignal/capistrano2_spec.rb
  spec/lib/appsignal/capistrano3_spec.rb
  spec/lib/appsignal/transmitter_spec.rb
  spec/support/helpers/config_helpers.rb
Labels: chore

#1307 Fix DSL config source in diagnose report
  .changesets/report-all-dsl-config-options-in-config-source.md
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: bug

#1308 Make config env, root path and options read only
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1309 Add reported_by tag to Rails error reporter errors
  .changesets/add-reported_by-tag-to-rails-error-reporter.md
  lib/appsignal/integrations/railtie.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
Labels: enhancement

#1310 Fix Pathname to String conversion error
  .changesets/fix-no-implicit-conversion-of-pathname-into-string-error.md
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
Labels: bug
