Repository appsignal/appsignal-ruby, pull requests merged in 2024-07, with the labels that each got.

#1131 Refactor test suite with transaction helpers
  spec/lib/appsignal/demo_spec.rb
  spec/lib/appsignal/hooks/action_cable_spec.rb
  spec/lib/appsignal/hooks/active_support_notifications/finish_with_state_shared_examples.rb
  spec/lib/appsignal/hooks/active_support_notifications/instrument_shared_examples.rb
  spec/lib/appsignal/hooks/active_support_notifications/start_finish_shared_examples.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
  spec/lib/appsignal/hooks/delayed_job_spec.rb
  spec/lib/appsignal/hooks/dry_monitor_spec.rb
  spec/lib/appsignal/hooks/excon_spec.rb
  spec/lib/appsignal/hooks/rake_spec.rb
  spec/lib/appsignal/hooks/redis_client_spec.rb
  spec/lib/appsignal/hooks/redis_spec.rb
  spec/lib/appsignal/hooks/resque_spec.rb
  spec/lib/appsignal/hooks/shoryuken_spec.rb
  spec/lib/appsignal/integrations/hanami_spec.rb
  spec/lib/appsignal/integrations/http_spec.rb
  spec/lib/appsignal/integrations/que_spec.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
  spec/lib/appsignal/rack/event_handler_spec.rb
  spec/lib/appsignal/rack/generic_instrumentation_spec.rb
  spec/lib/appsignal/rack/grape_middleware_spec.rb
  spec/lib/appsignal/rack/hanami_middleware_spec.rb
  spec/lib/appsignal/rack/rails_instrumentation_spec.rb
  spec/lib/appsignal/rack/sinatra_instrumentation_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/std_streams_helper.rb
  spec/support/matchers/be_completed.rb
  spec/support/matchers/transaction.rb
  spec/support/mocks/dummy_app.rb
  spec/support/shared_examples/instrument.rb
  spec/support/testing.rb
Labels: dev happiness

#1133 Fix internal memory logger warn_once_then_debug
  lib/appsignal/utils/integration_memory_logger.rb
  spec/lib/appsignal/utils/integration_memory_logger_spec.rb
Labels: bug

#1136 Remove last bits of Semaphore config and artifacts
  README.md
  Rakefile
  support/check_versions
Labels: chore

#1137 Add scheduled build to CI
  .github/workflows/ci.yml
  build_matrix.yml
Labels: chore

#1138 Remove default abstract instrumentation event
  lib/appsignal/rack/abstract_middleware.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
Labels: chore

#1145 Update JRuby to 9.4.7.0 in CI
  .github/workflows/ci.yml
  build_matrix.yml
Labels: chore

#1142 Use Rack middleware for Padrino instrumentation
  .changesets/report-response-status-for-padrino-apps.md
  .changesets/support-nested-padrino-apps.md
  lib/appsignal/integrations/padrino.rb
  spec/lib/appsignal/integrations/padrino_spec.rb
  spec/lib/appsignal/integrations/sinatra_spec.rb
Labels: enhancement

#1143 Fix Padrino instrumentation causing boot loop
  .changesets/padrino-boot-loop.md
  lib/appsignal/integrations/padrino.rb
  spec/lib/appsignal/integrations/padrino_spec.rb
Labels: bug

#1141 Support nested webmachine apps
  .changesets/support-nested-webmachine-apps.md
  gemfiles/webmachine1.gemfile
  lib/appsignal/integrations/webmachine.rb
  spec/lib/appsignal/integrations/webmachine_spec.rb
Labels: enhancement

#1139 Add new Rack instrumentation middleware
  .changesets/add-new-recommended-rack-instrumentation-middleware.md
  .changesets/deprecate-appsignal--rack--genericinstrumentation-middleware.md
  lib/appsignal.rb
  lib/appsignal/rack.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/generic_instrumentation.rb
  lib/appsignal/rack/instrumentation_middleware.rb
  lib/appsignal/rack/rails_instrumentation.rb
  lib/appsignal/rack/sinatra_instrumentation.rb
  spec/lib/appsignal/rack/generic_instrumentation_spec.rb
  spec/lib/appsignal/rack/grape_middleware_spec.rb
  spec/lib/appsignal/rack/instrumentation_middleware_spec.rb
Labels: enhancement

#1144 Add Appsignal.report_error helper
  .changesets/add-report_error-helper.md
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1148 Clarify tags are merged in tags helpers
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: chore

#1160 Update GitHub actions to run builds for forks
  .github/workflows/ci.yml
  build_matrix.yml
Labels: chore

#1159 Fix all_specs deprecation of bundler
  .changesets/fix-deprecation-of-bundler-rubygems-all_specs.md
  lib/appsignal/environment.rb
Labels: chore

#1157 Remove duplicate parameter filtering
  lib/appsignal/hooks/active_job.rb
  lib/appsignal/integrations/sidekiq.rb
Labels: chore

#1154 Add Appsignal.set_params helper
  .changesets/add-appsignal-set_params-helper.md
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1153 Add Appsignal.set_tags alias
  .changesets/add-appsignal-set_tags-helper.md
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1158 Optimize setting parameters for transactions
  .changesets/add-block-argument-to-set_params.md
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1146 Improve instrumentation middleware option naming and documentation
  lib/appsignal/integrations/padrino.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/generic_instrumentation.rb
  lib/appsignal/rack/grape_middleware.rb
  lib/appsignal/rack/hanami_middleware.rb
  lib/appsignal/rack/instrumentation_middleware.rb
  lib/appsignal/rack/rails_instrumentation.rb
  lib/appsignal/rack/sinatra_instrumentation.rb
  spec/lib/appsignal/integrations/padrino_spec.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
Labels: chore

#1155 Deprecate the request env keys to set the action
  .changesets/deprecate-appsignal-route-and-appsignal-action-request-env.md
  lib/appsignal/rack/abstract_middleware.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
Labels: chore

#1149 Add set_custom_data instrumentation helper
  .changesets/add-set_custom_data-helper.md
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1163 Specify visibility in API docs
  lib/appsignal/cli/demo.rb
  lib/appsignal/config.rb
  lib/appsignal/event_formatter.rb
  lib/appsignal/event_formatter/rom/sql_formatter.rb
  lib/appsignal/integrations/action_cable.rb
  lib/appsignal/integrations/active_support_notifications.rb
  lib/appsignal/integrations/data_mapper.rb
  lib/appsignal/integrations/dry_monitor.rb
  lib/appsignal/integrations/excon.rb
  lib/appsignal/integrations/http.rb
  lib/appsignal/integrations/net_http.rb
  lib/appsignal/integrations/object.rb
  lib/appsignal/integrations/que.rb
  lib/appsignal/integrations/redis.rb
  lib/appsignal/integrations/redis_client.rb
  lib/appsignal/integrations/resque.rb
  lib/appsignal/integrations/sidekiq.rb
  lib/appsignal/integrations/unicorn.rb
  lib/appsignal/logger.rb
  lib/appsignal/probes.rb
  lib/appsignal/probes/helpers.rb
  lib/appsignal/probes/mri.rb
  lib/appsignal/probes/sidekiq.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/event_handler.rb
  lib/appsignal/rack/generic_instrumentation.rb
  lib/appsignal/rack/grape_middleware.rb
  lib/appsignal/rack/streaming_listener.rb
  lib/appsignal/span.rb
  lib/appsignal/transaction.rb
  lib/appsignal/utils.rb
  lib/appsignal/utils/data.rb
  lib/appsignal/utils/hash_sanitizer.rb
  lib/appsignal/utils/integration_memory_logger.rb
  lib/appsignal/utils/json.rb
  lib/appsignal/utils/query_params_sanitizer.rb
  lib/appsignal/utils/stdout_and_logger_message.rb
Labels: chore

#1164 Move Capistrano integration class to namespace
  lib/appsignal/integrations/capistrano/capistrano_2_tasks.rb
  spec/lib/appsignal/capistrano2_spec.rb
Labels: chore

#1172 Fix typo in start_logger deprecation message
  lib/appsignal.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1173 Update benchmark task
  .rubocop.yml
  benchmark.rake
Labels: chore

#1166 Add sample data helpers
  .changesets/add-appsignal-set_headers-helper.md
  .changesets/add-appsignal-set_session_data-helper.md
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1169 Allow tags to contain boolean values
  .changesets/allow-booleans-in-tags.md
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: enhancement

#1162 Optimize setting Sidekiq job arguments
  .changesets/optimize-sidekiq-argumetns.md
  lib/appsignal/integrations/sidekiq.rb
Labels: enhancement

#1167 Deprecate Transaction sample data helpers
  .changesets/deprecate-transaction-sample-helpers.md
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/support/testing.rb
Labels: chore

#1177 Report request headers for webmachine apps
  .changesets/report-request-headers-for-webmachine-apps.md
  lib/appsignal/integrations/webmachine.rb
  spec/lib/appsignal/integrations/webmachine_spec.rb
Labels: chore

#1171 Refactor Delayed::Job integration to not use monitor_transaction
  lib/appsignal/hooks/delayed_job.rb
  lib/appsignal/integrations/delayed_job_plugin.rb
  spec/lib/appsignal/hooks/delayed_job_spec.rb
  spec/lib/appsignal/integrations/delayed_job_plugin_spec.rb
Labels: chore

#1178 Refactor Shoryuken to not use monitor_transaction
  lib/appsignal/hooks/shoryuken.rb
  lib/appsignal/integrations/shoryuken.rb
  spec/lib/appsignal/hooks/shoryuken_spec.rb
  spec/lib/appsignal/integrations/shoryuken_spec.rb
Labels: chore

#1175 Deprecate `set_http_or_background_queue_start`
  .changesets/deprecate--appsignal--transaction-set_http_or_background_queue_start-.md
  lib/appsignal/demo.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/integrations/sidekiq.rb
  lib/appsignal/rack.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/event_handler.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/rack_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/matchers/transaction.rb
Labels: chore

#1179 Refactor integrations to user transaction metadata helpers
  lib/appsignal/demo.rb
  lib/appsignal/integrations/que.rb
  lib/appsignal/integrations/webmachine.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/event_handler.rb
  spec/lib/appsignal/integrations/que_spec.rb
  spec/lib/appsignal/rack/event_handler_spec.rb
Labels: chore

#1180 Log errors when fetching sample data
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
  spec/lib/appsignal/rack/rails_instrumentation_spec.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: chore

#1181 Set Action Cable request metadata using helpers
  lib/appsignal/hooks/action_cable.rb
  spec/lib/appsignal/hooks/action_cable_spec.rb
Labels: chore

#1182 Set Action Cable request ID as a tag
  lib/appsignal/hooks/action_cable.rb
  lib/appsignal/integrations/action_cable.rb
  spec/lib/appsignal/hooks/action_cable_spec.rb
Labels: chore

#1183 Set job ID as request_id tag
  lib/appsignal/hooks/active_job.rb
  lib/appsignal/integrations/sidekiq.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
Labels: chore

#1185 Remove the warn_once_then_debug from the logger
  lib/appsignal/transaction.rb
  lib/appsignal/utils/integration_logger.rb
  lib/appsignal/utils/integration_memory_logger.rb
  spec/lib/appsignal/utils/integration_logger_spec.rb
  spec/lib/appsignal/utils/integration_memory_logger_spec.rb
Labels: chore

#1186 Remove Action Cable dependency on request object
  lib/appsignal/integrations/action_cable.rb
  spec/lib/appsignal/hooks/action_cable_spec.rb
Labels: chore

#1176 Add ignore_instrumentation_events helper
  .changesets/deprecate--appsignal-without_instrumentation--helper-.md
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1184 Update transaction creation
  .changesets/deprecate-arguments-for-transaction-create-and-transaction-new.md
  .changesets/deprecate-genericrequest-usage-.md
  benchmark.rake
  lib/appsignal/demo.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/hooks/action_cable.rb
  lib/appsignal/hooks/active_job.rb
  lib/appsignal/integrations/action_cable.rb
  lib/appsignal/integrations/delayed_job_plugin.rb
  lib/appsignal/integrations/que.rb
  lib/appsignal/integrations/rake.rb
  lib/appsignal/integrations/resque.rb
  lib/appsignal/integrations/shoryuken.rb
  lib/appsignal/integrations/sidekiq.rb
  lib/appsignal/integrations/webmachine.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/event_handler.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/hooks/action_cable_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/support/helpers/transaction_helpers.rb
Labels: chore

#1187 Refactor config env vars mapping
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: chore

#1161 Add monitor instrumentation helpers
  .changesets/add-monitor-helper.md
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
  spec/support/matchers/transaction.rb
Labels: enhancement

#1188 Deprecate the monitor_transaction helpers
  .changesets/deprecate-appsignal-monitor_transaction-helper.md
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1189 Small improvements for next release
  .changesets/add-monitor-helper.md
  .changesets/deprecate--appsignal--transaction-set_http_or_background_queue_start-.md
  .changesets/deprecate-appsignal-monitor_transaction-helper.md
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: chore

#1191 Bunch of tiny improvements
  lib/appsignal.rb
  spec/lib/appsignal/integrations/grape_spec.rb
  spec/lib/appsignal/rack/grape_middleware_spec.rb
  spec/lib/appsignal/rack/sinatra_instrumentation_spec.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1193 Disable EventHandler when AppSignal is not active
  .changesets/disable-eventhandler-when-appsignal-is-not-active-.md
  lib/appsignal/rack/event_handler.rb
  spec/lib/appsignal/rack/event_handler_spec.rb
Labels: enhancement

#1194 Fix duplicate response body instrumentation events
  .changesets/don-t-instrument-response-bodies-twice.md
  lib/appsignal/rack.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/event_handler.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
Labels: bug

#1195 Update specs to not use deprecated methods
  spec/lib/appsignal/hooks/active_support_notifications_spec.rb
  spec/lib/appsignal/hooks/dry_monitor_spec.rb
  spec/lib/appsignal/hooks/excon_spec.rb
  spec/lib/appsignal/hooks/redis_client_spec.rb
  spec/lib/appsignal/hooks/redis_spec.rb
  spec/lib/appsignal/hooks/sequel_spec.rb
  spec/lib/appsignal/integrations/mongo_ruby_driver_spec.rb
Labels: chore

#1190 Rails apps can configure AppSignal in initializers
  .changesets/start-appsignal-after-rails-is-initialized.md
  lib/appsignal/integrations/railtie.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
  spec/support/helpers/config_helpers.rb
Labels: enhancement

#1192 Add loader mechanism
  .changesets/update-sinatra-integration-setup.md
  lib/appsignal.rb
  lib/appsignal/config.rb
  lib/appsignal/integrations/grape.rb
  lib/appsignal/integrations/hanami.rb
  lib/appsignal/integrations/padrino.rb
  lib/appsignal/integrations/sinatra.rb
  lib/appsignal/loaders.rb
  lib/appsignal/loaders/grape.rb
  lib/appsignal/loaders/hanami.rb
  lib/appsignal/loaders/padrino.rb
  lib/appsignal/loaders/sinatra.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/integrations/hanami_spec.rb
  spec/lib/appsignal/integrations/padrino_spec.rb
  spec/lib/appsignal/integrations/sinatra_spec.rb
  spec/lib/appsignal/loaders/grape_spec.rb
  spec/lib/appsignal/loaders/hanami_spec.rb
  spec/lib/appsignal/loaders/padrino_spec.rb
  spec/lib/appsignal/loaders/sinatra_spec.rb
  spec/lib/appsignal/loaders_spec.rb
  spec/lib/appsignal_spec.rb
  spec/spec_helper.rb
  spec/support/helpers/loader_helper.rb
  spec/support/stubs/appsignal/loaders/loader_stub.rb
  spec/support/testing.rb
Labels: enhancement

#1196 Add Appsignal.configure helper
  .changesets/add-appsignal-configure.md
  .changesets/deprecate-appsignal-config---.md
  Rakefile
  lib/appsignal.rb
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/config.rb
  lib/appsignal/demo.rb
  lib/appsignal/integrations/railtie.rb
  spec/lib/appsignal/cli/demo_spec.rb
  spec/lib/appsignal/cli/diagnose/paths_spec.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/demo_spec.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
  spec/lib/appsignal/hooks/gvl_spec.rb
  spec/lib/appsignal/hooks/redis_client_spec.rb
  spec/lib/appsignal/hooks/redis_spec.rb
  spec/lib/appsignal/hooks/resque_spec.rb
  spec/lib/appsignal/hooks/sidekiq_spec.rb
  spec/lib/appsignal/integrations/delayed_job_plugin_spec.rb
  spec/lib/appsignal/integrations/object_spec.rb
  spec/lib/appsignal/integrations/shoryuken_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
  spec/lib/appsignal/probes/sidekiq_spec.rb
  spec/lib/appsignal_spec.rb
  spec/spec_helper.rb
  spec/support/helpers/config_helpers.rb
  spec/support/testing.rb
Labels: enhancement

#1197 Refactor config in specs
  spec/lib/appsignal/cli/demo_spec.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/lib/appsignal/environment_spec.rb
  spec/lib/appsignal/hooks/excon_spec.rb
  spec/lib/appsignal/hooks/http_spec.rb
  spec/lib/appsignal/hooks/net_http_spec.rb
  spec/lib/appsignal/hooks/redis_spec.rb
  spec/lib/appsignal/hooks/sequel_spec.rb
  spec/lib/appsignal/hooks/webmachine_spec.rb
  spec/lib/appsignal/integrations/http_spec.rb
  spec/lib/appsignal/integrations/net_http_spec.rb
  spec/lib/appsignal/integrations/object_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
  spec/lib/appsignal/probes_spec.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
  spec/lib/appsignal/rack/generic_instrumentation_spec.rb
  spec/lib/appsignal/rack/grape_middleware_spec.rb
  spec/lib/appsignal/rack/hanami_middleware_spec.rb
  spec/lib/appsignal/rack/sinatra_instrumentation_spec.rb
  spec/lib/appsignal/span_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
  spec/lib/puma/appsignal_spec.rb
  spec/spec_helper.rb
  spec/support/testing.rb
Labels: dev happiness

#1199 Refactor Transaction set_error specs
  spec/lib/appsignal/transaction_spec.rb
  spec/support/matchers/transaction.rb
Labels: chore

#1204 Refactor config options set in specs
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
  spec/lib/appsignal/hooks/gvl_spec.rb
  spec/lib/appsignal/hooks/http_spec.rb
  spec/lib/appsignal/hooks/net_http_spec.rb
  spec/lib/appsignal/hooks/rake_spec.rb
  spec/lib/appsignal/hooks/redis_client_spec.rb
  spec/lib/appsignal/hooks/redis_spec.rb
  spec/lib/appsignal/hooks/resque_spec.rb
  spec/lib/appsignal/integrations/delayed_job_plugin_spec.rb
  spec/lib/appsignal/integrations/shoryuken_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/support/fixtures/projects/valid/config/appsignal.yml
  spec/support/helpers/config_helpers.rb
Labels: chore

#1206 Add macOS build to CI
  .github/workflows/ci.yml
  Rakefile
  build_matrix.yml
  gemfiles/que_beta.gemfile
  spec/lib/appsignal/extension_install_failure_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: chore

#1207 Small spec refactor
  spec/lib/appsignal/hooks/active_support_notifications/instrument_shared_examples.rb
  spec/lib/appsignal/hooks/active_support_notifications/start_finish_shared_examples.rb
  spec/lib/appsignal/hooks/active_support_notifications_spec.rb
  spec/lib/appsignal/probes_spec.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
  spec/lib/appsignal/rack/event_handler_spec.rb
  spec/lib/appsignal/rack/sinatra_instrumentation_spec.rb
  spec/support/fixtures/projects/valid/config/appsignal.yml
  spec/support/helpers/config_helpers.rb
  spec/support/mocks/mock_probe.rb
Labels: chore

#1208 Update datamapper spec to use new matchers
  spec/lib/appsignal/integrations/data_mapper_spec.rb
Labels: chore

#1202 Change default Rake task namespace to rake
  .changesets/rake-task-namespace.md
  lib/appsignal/integrations/rake.rb
  spec/lib/appsignal/hooks/rake_spec.rb
Labels: enhancement

#1201 Do not start when file source raises an error
  .changesets/do-not-start-on-config-file-error.md
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: enhancement

#1203 Freeze config on AppSignal start
  .changesets/freeze-config-after-appsignal-has-started.md
  lib/appsignal.rb
  lib/appsignal/config.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1205 Report Rails runner errors
  .changesets/report-errors-from-rails-runners.md
  lib/appsignal/integrations/railtie.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: enhancement

#1211 Fix `.monitor_and_stop` block passing
  .changesets/fix-appsignal-monitor_and_stop-block-passing.md
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
Labels: bug

#1214 Fix loader defaults from overriding other sources
  .changesets/fix-default-env-and-root-path-for-integrations-using-loader-mechanism.md
  lib/appsignal.rb
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/config_helpers.rb
Labels: bug

#1217 Ignore calls to start AppSignal twice
  .changesets/do-not-start-appsignal-multiple-times-if--appsignal-start--is-called-more-than-once.md
  lib/appsignal.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1210 Multiple errors support
  .changesets/fix-an-issue-where-error-causes-for-the-wrong-error-would-be-shown.md
  .changesets/support-adding-multiple-errors-to-a-transaction.md
  ext/agent.rb
  ext/appsignal_extension.c
  lib/appsignal/extension/jruby.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/extension_spec.rb
  spec/lib/appsignal/integrations/data_mapper_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/transaction_helpers.rb
Labels: enhancement

#1219 Fix app env being reported as empty brackets
  .changesets/fix-env-being-reported-as-----.md
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: bug

#1220 Fix configure call without env when it has config
  .changesets/fix-configure-config-reuse.md
  lib/appsignal.rb
  spec/lib/appsignal_spec.rb
Labels: bug
