Repository appsignal/appsignal-ruby, pull requests merged in 2024-05, with the labels that each got.

#1074 Fix deprecation warning
  .changesets/fix-deprecation-warnings-for-probes-probes.md
  lib/appsignal/hooks/gvl.rb
  lib/appsignal/hooks/mri.rb
  lib/appsignal/hooks/sidekiq.rb
Labels: bug

#1075 Rename perform_job methods in spec
  Gemfile
  gemfiles/no_dependencies.gemfile
  gemfiles/rails-6.0.gemfile
  gemfiles/rails-6.1.gemfile
  gemfiles/rails-7.0.gemfile
  gemfiles/rails-7.1.gemfile
  spec/lib/appsignal/hooks/activejob_spec.rb
  spec/lib/appsignal/hooks/resque_spec.rb
  spec/lib/appsignal/hooks/shoryuken_spec.rb
  spec/lib/appsignal/integrations/que_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
Labels: chore

#1079 Fix LocalJumpError for Active Job < 7.1
  .changesets/fix-localjumperror-in-active-job-instrumentation.md
  lib/appsignal/hooks/active_job.rb
Labels: bug

#1081 Print test names in CI
  Rakefile
Labels: dev happiness

#1082 Add ViewComponent event formatter
  .changesets/support-viewcomponent-events.md
  gemfiles/rails-7.1.gemfile
  lib/appsignal/event_formatter/view_component/render_formatter.rb
  spec/lib/appsignal/event_formatter/view_component/render_formatter_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: enhancement

#1083 Do not use `trace` on internal logger
  .changesets/fix-issue-when-sending-heartbeats.md
  lib/appsignal/heartbeat.rb
  spec/lib/appsignal/heartbeat_spec.rb
Labels: bug

#1086 Improve probe specs
  spec/lib/appsignal/probes_spec.rb
Labels: chore

#1085 Document the heartbeat functionality
  lib/appsignal.rb
  lib/appsignal/heartbeat.rb
  lib/appsignal/helpers/heartbeats.rb
Labels: chore

#1088 Log error when probes iteration takes too long
  .changesets/log-slow-probes-error.md
  lib/appsignal/probes.rb
  spec/lib/appsignal/probes_spec.rb
Labels: enhancement

#1087 Improve AppSignal loaded log
  lib/appsignal.rb
Labels: chore
