Repository appsignal/appsignal-ruby, pull requests merged in 2024-08, with the labels that each got.

#1226 Always register ViewComponent event formatter
  .changesets/fix-viewcomponent-instrumentation-not-loading.md
  gemfiles/rails-7.1.gemfile
  lib/appsignal/event_formatter/view_component/render_formatter.rb
  spec/lib/appsignal/event_formatter/view_component/render_formatter_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: bug

#1223 Installer improvements
  .changesets/fix-error-on-padrino-require.md
  .changesets/install-for-unknown-frameworks.md
  lib/appsignal/cli/install.rb
  spec/lib/appsignal/cli/install_spec.rb
Labels: enhancement

#1229 Deprecate Appsignal.listen_for_error helper
  .changesets/deprecate-appsignal-listen_for_error.md
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1228 Add option to customize config root path
  .changesets/deprecate-config-app_path-writer-.md
  .changesets/fix-appsignal-configure-path-config.md
  lib/appsignal.rb
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal_spec.rb
Labels: bug

#1221 Add error block
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1230 Remove listen_for_error helper
  .changesets/remove-listen_for_error-helper.md
  lib/appsignal/helpers/instrumentation.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1231 Remove FRONTEND namespace constant
  .changesets/remove--private--appsignal--transaction--frontend-constant.md
  lib/appsignal/transaction.rb
Labels: chore

#1209 Allow merging of sample data
  .changesets/merge-sample-data.md
  benchmark.rake
  lib/appsignal.rb
  lib/appsignal/demo.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/hooks/action_cable.rb
  lib/appsignal/hooks/active_job.rb
  lib/appsignal/integrations/action_cable.rb
  lib/appsignal/integrations/delayed_job_plugin.rb
  lib/appsignal/integrations/que.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/integrations/rake.rb
  lib/appsignal/integrations/resque.rb
  lib/appsignal/integrations/shoryuken.rb
  lib/appsignal/integrations/sidekiq.rb
  lib/appsignal/integrations/webmachine.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/event_handler.rb
  lib/appsignal/rack/rails_instrumentation.rb
  lib/appsignal/sample_data.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
  spec/lib/appsignal/sample_data_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/matchers/transaction.rb
Labels: enhancement

#1232 Register Rails config defaults using loader
  .changesets/set-rails-config-defaults-for-appsignal-configure.md
  lib/appsignal/config.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/loaders.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
  spec/lib/appsignal/loaders/hanami_spec.rb
  spec/lib/appsignal/loaders/padrino_spec.rb
  spec/lib/appsignal/loaders/sinatra_spec.rb
  spec/lib/appsignal/loaders_spec.rb
Labels: enhancement

#1233 Refactor diagnose CLI specs
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/support/helpers/api_request_helper.rb
Labels: chore

#1234 Refactor Rails behavior in diagnose spec
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/support/fixtures/projects/valid/config/environments/production.rb
  spec/support/fixtures/projects/valid/config/environments/test.rb
  spec/support/fixtures/projects/valid_with_rails_app/config/application.rb
  spec/support/fixtures/projects/valid_with_rails_app/config/appsignal.yml
  spec/support/fixtures/projects/valid_with_rails_app/log/.gitkeep
  spec/support/helpers/config_helpers.rb
Labels: chore

#1236 A couple test suite refactors
  spec/lib/appsignal/cli/demo_spec.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/hooks/activejob_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
  spec/lib/appsignal/rack/event_handler_spec.rb
  spec/lib/appsignal/rack/rails_instrumentation_spec.rb
  spec/support/helpers/log_helpers.rb
Labels: chore

#1216 Make global helpers work in error method callbacks
  .changesets/global-helpers-work-inside-report_error-and-send_error-callbacks.md
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal_spec.rb
Labels: enhancement

#1239 Do not report HTTP gem errors
  .changesets/remove-http-gem-exception-handling.md
  lib/appsignal/integrations/http.rb
  spec/lib/appsignal/integrations/http_spec.rb
Labels: enhancement

#1240 Use report_error in Rails error subscriber
  lib/appsignal/integrations/railtie.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
  spec/lib/appsignal/integrations/sidekiq_spec.rb
Labels: enhancement

#1225 Load Rails config in diagnose CLI
  .changesets/include-rails-app-config-in-diagnose-report.md
  lib/appsignal.rb
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/utils/rails_helper.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
  spec/spec_helper.rb
  spec/support/fixtures/projects/valid_with_rails_app/config/application.rb
  spec/support/fixtures/projects/valid_with_rails_app/config/environment.rb
  spec/support/helpers/config_helpers.rb
  spec/support/helpers/rails_helper.rb
  spec/support/rails/my_app.rb
Labels: enhancement

#1238 Remove Appsignal._config= writer
  .changesets/remove-appsignal-config--writer.md
  lib/appsignal.rb
  lib/appsignal/config.rb
  lib/appsignal/integrations/capistrano/appsignal.cap
  lib/appsignal/integrations/capistrano/capistrano_2_tasks.rb
  spec/lib/appsignal/auth_check_spec.rb
  spec/lib/appsignal/capistrano2_spec.rb
  spec/lib/appsignal/capistrano3_spec.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/extension_spec.rb
  spec/lib/appsignal/marker_spec.rb
  spec/lib/appsignal/transmitter_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/api_request_helper.rb
  spec/support/helpers/config_helpers.rb
  spec/support/mocks/appsignal_mock.rb
Labels: chore

#1241 Bump Ruby versions in the CI
  .github/workflows/ci.yml
  build_matrix.yml
Labels: chore

#1242 Add Rails 7.2 to CI build
  .github/workflows/ci.yml
  build_matrix.yml
  gemfiles/rails-7.2.gemfile
Labels: chore

#1115 Rename heartbeats to cron check-ins
  .changesets/deprecate-heartbeats.md
  .changesets/rename-heartbeats-to-cron-check-ins.md
  lib/appsignal.rb
  lib/appsignal/check_in.rb
  lib/appsignal/check_in/cron.rb
  lib/appsignal/heartbeat.rb
  lib/appsignal/helpers/heartbeat.rb
  lib/appsignal/helpers/heartbeats.rb
  spec/lib/appsignal/check_in_spec.rb
  spec/lib/appsignal/heartbeat_spec.rb
Labels: chore

#1244 Bump agent to version 0.35.21
  .changesets/calculate-error-rate-by-errors-on-a-transaction.md
  ext/agent.rb
Labels: enhancement

#1243 Remove heartbeat aliases and warnings
  lib/appsignal.rb
  lib/appsignal/check_in/cron.rb
  lib/appsignal/helpers/heartbeat.rb
  spec/lib/appsignal/check_in_spec.rb
Labels: chore

#1246 Tiny installer improvements
  lib/appsignal/cli/install.rb
Labels: chore

#1249 Add helper to unset parameters sample data
  .changesets/allow-parameters-to-be-unset.md
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/sample_data.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/sample_data_spec.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1250 Remove Transaction ID argument for initializer
  .changesets/remove-transaction-id-argument.md
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/support/helpers/transaction_helpers.rb
Labels: chore

#1251 Fix default transaction store value
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: bug

#1252 Improve API docs for Ruby gem
  lib/appsignal.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/helpers/metrics.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1253 Assert DSL config source in diagnose specs
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/support/fixtures/projects/valid_with_rails_app/config/environment.rb
Labels: chore

#1254 Ignore closed pipe error in response body wrapper
  .changesets/ignore-errno--epipe-when-instrumenting-response-bodies.md
  lib/appsignal/rack/body_wrapper.rb
  spec/lib/appsignal/rack/body_wrapper_spec.rb
Labels: bug

#1255 Small refactors and cleanup
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
  spec/support/testing.rb
Labels: chore

#1256 Do not report `Sidekiq::JobRetry::Skip` errors
  .changesets/do-not-report-sidekiq--jobretry--skip-errors.md
  lib/appsignal/integrations/railtie.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
Labels: bug

#1257 Do not report SystemExit errors in at_exit handler
  .changesets/do-not-report-systemexit-errors-from-our--at_exit--error-reporter.md
  lib/appsignal/hooks/at_exit.rb
  spec/lib/appsignal/hooks/at_exit_spec.rb
Labels: bug

#1258 Split Resque tests per module
  spec/lib/appsignal/hooks/resque_spec.rb
  spec/lib/appsignal/integrations/resque_spec.rb
Labels: chore

#1259 Fix Rails session data not being reported
  .changesets/do-not-log-warning-for-nil-data-in-sample-data-but-silently-ignore-it.md
  .changesets/fix-rails-session-data-not-being-reported.md
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/sample_data.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
  spec/lib/appsignal/sample_data_spec.rb
Labels: bug

#1261 Remove deprecated app_path config DSL writer
  .changesets/remove-app_path-writer-in-appsignal-configure-helper.md
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: chore

#1264 Test Bundler installed gems methods
  spec/lib/appsignal/environment_spec.rb
Labels: chore

#1262 Do not report internal Sidekiq errors
  .changesets/do-not-report-sidekiq-internal-errors.md
  lib/appsignal/integrations/railtie.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
Labels: bug

#1245 Check-in scheduler
  .changesets/send-check-ins-concurrently.md
  lib/appsignal.rb
  lib/appsignal/check_in.rb
  lib/appsignal/check_in/cron.rb
  lib/appsignal/check_in/scheduler.rb
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/transmitter.rb
  lib/appsignal/utils.rb
  lib/appsignal/utils/ndjson.rb
  spec/lib/appsignal/check_in/cron_spec.rb
  spec/lib/appsignal/check_in/scheduler_spec.rb
  spec/lib/appsignal/check_in_spec.rb
  spec/lib/appsignal/transmitter_spec.rb
  spec/lib/appsignal_spec.rb
  spec/support/helpers/take_at_most_helper.rb
Labels: enhancement

#1268 Fix spec that fetches gems from Bundler
  spec/lib/appsignal/environment_spec.rb
Labels: chore

#1266 Fix error calling body methods on BodyWrapper
  .changesets/make-our-rack-bodywrapper-behave-like-a-rack-bodyproxy.md
  lib/appsignal/rack/body_wrapper.rb
  spec/lib/appsignal/rack/body_wrapper_spec.rb
Labels: bug

#1267 Do not report `SignalException` in at_exit handler
  .changesets/do-not-report--signalexception-from-our--at_exit--error-reporter-.md
  lib/appsignal/hooks/at_exit.rb
  spec/lib/appsignal/hooks/at_exit_spec.rb
Labels: bug
