Repository appsignal/appsignal-ruby, pull requests merged in 2024-06, with the labels that each got.

#1094 Fix compatibility with Rack 3.1.0
  gemfiles/grape.gemfile
  spec/lib/appsignal/transaction_spec.rb
Labels: chore

#1092 Bump agent to version 0.35.12
  .changesets/internal-agent-changes-for-ruby-gem.md
  ext/agent.rb
Labels: enhancement

#1093 Notify changelog repo of new releases
  .github/workflows/create_release_from_tag.yml
Labels: dev happiness

#1089 Improve Rails/Rack request instrumentation
  .changesets/report-rails-request-middleware-in-request-duration.md
  lib/appsignal.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/rack/event_handler.rb
  lib/appsignal/rack/rails_instrumentation.rb
  spec/lib/appsignal/rack/event_handler_spec.rb
  spec/lib/appsignal/rack/rails_instrumentation_spec.rb
Labels: enhancement

#1096 Fix ArgumentError on other non-String log messages
  .changesets/fix-argumenterror-on-rails-logger-error-call.md
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: bug

#1090 Report request response status for Rails apps
  .changesets/report-response-status-for-rails-requests.md
  lib/appsignal/rack/event_handler.rb
  spec/lib/appsignal/rack/event_handler_spec.rb
Labels: enhancement

#1098 Skip RubyGems and Bundler update on JRuby
  support/install_deps
Labels: chore

#1097 Improve nested Sinatra app instrumentation
  .changesets/improve-mounted-sinatra-apps-in-rails-apps-instrumentation.md
  lib/appsignal/rack/sinatra_instrumentation.rb
  spec/lib/appsignal/rack/sinatra_instrumentation_spec.rb
Labels: enhancement

#1101 Supported nested Rack EventHandlers
  .changesets/support-nested-rack-eventhandlers.md
  lib/appsignal/rack/event_handler.rb
  spec/lib/appsignal/rack/event_handler_spec.rb
Labels: enhancement

#1103 Fix APPSIGNAL_ACTIVEJOB_REPORT_ERRORS var naming
  lib/appsignal/config.rb
Labels: bug

#1100 Improve support for nested Rack middlewares
  .changesets/support-nested-genericinstrumentation-middleware.md
  lib/appsignal.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/generic_instrumentation.rb
  lib/appsignal/rack/sinatra_instrumentation.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
  spec/lib/appsignal/rack/generic_instrumentation_spec.rb
  spec/lib/appsignal/rack/sinatra_instrumentation_spec.rb
Labels: enhancement

#1105 Fix Sinatra instrumentation causing boot loop
  .changesets/don-t-start-for-sinatra-if-already-started.md
  lib/appsignal/integrations/sinatra.rb
  spec/lib/appsignal/integrations/sinatra_spec.rb
Labels: bug

#1109 Fix parameter reporting for Rack and Sinatra app
  .changesets/fix-parameter-reporting-for-rack-and-sinatra-apps.md
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: bug

#1111 Refactor Hanami specs to use Transaction#to_h
  lib/appsignal/integrations/hanami.rb
  spec/lib/appsignal/integrations/hanami_spec.rb
  spec/support/hanami/hanami_app.rb
Labels: dev happiness

#1110 Fix Transaction#params= deprecation warning
  .changesets/remove-internal-deprecate-params--usage.md
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/hooks/active_job.rb
  lib/appsignal/integrations/action_cable.rb
  lib/appsignal/integrations/hanami.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/integrations/resque.rb
  lib/appsignal/integrations/sidekiq.rb
  lib/appsignal/rack/rails_instrumentation.rb
  spec/lib/appsignal/rack/rails_instrumentation_spec.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: bug

#1113 Update Hanami to use Rack middleware
  .changesets/report-response_status-tag-and-metric-for-hanami-requests.md
  lib/appsignal/integrations/hanami.rb
  lib/appsignal/rack/hanami_middleware.rb
  spec/lib/appsignal/integrations/hanami_spec.rb
  spec/lib/appsignal/rack/hanami_middleware_spec.rb
Labels: enhancement

#1114 Fix error in EventHandler on request with error
  .changesets/fix-error-reporting-for-requests-with-an-error.md
  lib/appsignal/rack/event_handler.rb
  spec/lib/appsignal/rack/event_handler_spec.rb
Labels: bug

#1119 Deprecate Appsignal.start_logger
  .changesets/deprecate-appsignal-start_logger.md
  lib/appsignal.rb
  lib/appsignal/cli/diagnose.rb
  lib/appsignal/config.rb
  lib/appsignal/integrations/hanami.rb
  lib/appsignal/integrations/padrino.rb
  lib/appsignal/integrations/railtie.rb
  lib/appsignal/integrations/sinatra.rb
  spec/lib/appsignal/integrations/hanami_spec.rb
  spec/lib/appsignal/integrations/padrino_spec.rb
  spec/lib/appsignal/integrations/sinatra_spec.rb
  spec/lib/appsignal_spec.rb
Labels: chore

#1117 Move the Grape middleware to the rack directory
  .changesets/deprecate-appsignal--grape--middleware.md
  lib/appsignal/integrations/grape.rb
  lib/appsignal/rack/grape_middleware.rb
  spec/lib/appsignal/probes_spec.rb
  spec/lib/appsignal/rack/grape_middleware_spec.rb
Labels: chore

#1107 Use AbstractMiddleware for Rails middleware
  .changesets/fix-issue-with-invalid-request-methods-raising-an-error.md
  lib/appsignal.rb
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/event_handler.rb
  lib/appsignal/rack/rails_instrumentation.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
  spec/lib/appsignal/rack/rails_instrumentation_spec.rb
Labels: enhancement

#1118 Support nested Grape apps
  .changesets/support-nested-grape-apps.md
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/grape_middleware.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
  spec/lib/appsignal/rack/grape_middleware_spec.rb
Labels: enhancement

#1122 Require appsignal in Grape integration file
  .changesets/require-appsignal-in-grape-integration-file.md
  lib/appsignal/integrations/grape.rb
Labels: enhancement

#1123 Update Rubocop to version 1.64.1
  .rubocop.yml
  .rubocop_todo.yml
  Rakefile
  appsignal.gemspec
  ext/base.rb
  lib/appsignal/environment.rb
  lib/appsignal/extension/jruby.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/integrations/padrino.rb
  lib/appsignal/probes.rb
  lib/appsignal/probes/sidekiq.rb
  spec/.rubocop.yml
  spec/lib/appsignal/cli/install_spec.rb
  spec/lib/appsignal/hooks/active_support_notifications_spec.rb
  spec/lib/appsignal/probes_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: dev happiness

#1126 Remove deprecated start_logger method call
  lib/appsignal/demo.rb
Labels: bug

#1129 Add process name and ID tags to GVL metrics
  .changesets/report-gvl-metrics-per-process.md
  lib/appsignal/probes/gvl.rb
  spec/lib/appsignal/probes/gvl_spec.rb
Labels: enhancement

#1124 Don't report middleware event for Rails
  lib/appsignal/rack/abstract_middleware.rb
  lib/appsignal/rack/rails_instrumentation.rb
  spec/lib/appsignal/rack/abstract_middleware_spec.rb
  spec/lib/appsignal/rack/rails_instrumentation_spec.rb
Labels: chore

#1125 Report response status when there is no response
  .changesets/track-error-response-status.md
  lib/appsignal/rack/event_handler.rb
  spec/lib/appsignal/rack/event_handler_spec.rb
Labels: enhancement

#1128 Fix support for Hanami 2.1
  .changesets/support-hanami-2-1.md
  .semaphore/semaphore.yml
  build_matrix.yml
  gemfiles/hanami-2.0.gemfile
  gemfiles/hanami-2.1.gemfile
  lib/appsignal/rack/hanami_middleware.rb
  spec/lib/appsignal/integrations/hanami_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: bug

#1130 Fix Hanami instrumentation causing boot loop
  .changesets/don-t-start-for-hanami-if-already-started.md
  lib/appsignal/integrations/hanami.rb
  spec/lib/appsignal/integrations/hanami_spec.rb
Labels: bug
