Repository appsignal/appsignal-ruby, pull requests merged in 2024-12, with the labels that each got.

#1342 Fix JRuby jar-dependencies gem install issue
  gemfiles/rails-7.1.gemfile
  gemfiles/rails-7.2.gemfile
Labels: chore

#1339 Move up creation of Rack instrumentation event
  .changesets/reduce-rack-transaction-event-creation.md
  lib/appsignal/rack/event_handler.rb
Labels: enhancement

#1340 Add Ruby 3.4 preview 2 to the CI
  .github/workflows/ci.yml
  .gitignore
  build_matrix.yml
  gemfiles/padrino.gemfile
  gemfiles/rails-7.0.gemfile
  gemfiles/webmachine2.gemfile
  lib/appsignal/probes/sidekiq.rb
  spec/lib/appsignal/event_formatter/elastic_search/search_formatter_spec.rb
  spec/lib/appsignal/probes/sidekiq_spec.rb
  spec/lib/appsignal/utils/data_spec.rb
  spec/support/helpers/dependency_helper.rb
Labels: chore

#1346 Initialise check-in singletons under mutexes
  .changesets/make-check-in-scheduler-thread-safe.md
  lib/appsignal/check_in.rb
  lib/appsignal/check_in/scheduler.rb
Labels: bug

#1344 Add ActiveSupport tagged logging support
  .changesets/add-rails-activesupport-tagged-logging.md
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: enhancement

#1347 Add Ruby 3.4 RC 1 to the CI
  .github/workflows/ci.yml
  build_matrix.yml
Labels: chore

#1350 Fix tagged logging push_tags for Rails 8
  .changesets/fix-tagged-logging-for-rails-8.md
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: bug

#1351 Fix usage of `Appsignal::Logger#tagged` with several tags
  .changesets/fix--appsignal--logger-tagged--with-several-tags.md
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: chore

#1354 Allow `#tagged` to be called without a block
  .changesets/allow--logger-tagged--to-be-called-without-a-block.md
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: bug

#1355 Remove tagged logging support
  .changesets/allow--logger-tagged--to-be-called-without-a-block.md
  .changesets/fix--appsignal--logger-tagged--with-several-tags.md
  .changesets/remove-tagged-logging-support.md
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: chore

#1356 Implement silence logger functionality
  .changesets/fix---silence--implementation-for-logger.md
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: chore

#1361 Set formatter on all broadcasted loggers
  .changesets/fix-double-newlines-in-broadcasted-loggers.md
  lib/appsignal/logger.rb
  spec/lib/appsignal/logger_spec.rb
Labels: bug
