Repository appsignal/appsignal-ruby, pull requests merged in 2024-10, with the labels that each got.

#1314 Fix session data for Action Cable callbacks
  .changesets/fix-session-data-for-action-cable-callbacks.md
  lib/appsignal/hooks/action_cable.rb
  lib/appsignal/integrations/action_cable.rb
  spec/lib/appsignal/hooks/action_cable_spec.rb
  spec/support/helpers/env_helpers.rb
Labels: bug

#1316 Fix heartbeat test bug
  spec/lib/appsignal/check_in/heartbeat_spec.rb
Labels: bug

#1318 Send error causes line number as integer
  lib/appsignal/transaction.rb
  spec/lib/appsignal/transaction_spec.rb
Labels: chore

#1320 Refactor config option types
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: chore

#1321 Automatically ignore Rails' health-check
  .changesets/ignore-rails-healthcheck-by-default.md
  lib/appsignal/config.rb
  lib/appsignal/integrations/railtie.rb
  spec/lib/appsignal/cli/diagnose_spec.rb
  spec/lib/appsignal/config_spec.rb
  spec/lib/appsignal/integrations/railtie_spec.rb
Labels: enhancement

#1322 Refactor same config detection
  lib/appsignal.rb
Labels: chore
