Repository appsignal/appsignal-ruby, pull requests merged in 2025-04, with the labels that each got.

#1402 Close known transactions in EventHandler
  .changesets/ensure-request-transactions-are-always-closed.md
  lib/appsignal/rack/event_handler.rb
Labels: bug

#1407 Remove redundant cron check-in pairs
  lib/appsignal/check_in/event.rb
  lib/appsignal/check_in/scheduler.rb
  spec/lib/appsignal/check_in/event_spec.rb
Labels: bug, chore

#1408 Add Ruby 3.5.0-preview1 to the CI
  .github/workflows/ci.yml
  build_matrix.yml
  gemfiles/capistrano2.gemfile
  gemfiles/dry-monitor.gemfile
  gemfiles/grape.gemfile
  gemfiles/hanami-2.0.gemfile
  gemfiles/hanami-2.1.gemfile
  gemfiles/hanami-2.2.gemfile
  gemfiles/http5.gemfile
  gemfiles/no_dependencies.gemfile
  gemfiles/ownership.gemfile
  gemfiles/padrino.gemfile
  gemfiles/psych-3.gemfile
  gemfiles/psych-4.gemfile
  gemfiles/que-1.gemfile
  gemfiles/que-2.gemfile
  gemfiles/rails-7.0.gemfile
  gemfiles/rails-7.1.gemfile
  gemfiles/rails-7.2.gemfile
  gemfiles/rails-8.0.gemfile
  gemfiles/redis-4.gemfile
  gemfiles/redis-5.gemfile
  gemfiles/sequel.gemfile
  gemfiles/sidekiq-7.gemfile
  gemfiles/sidekiq-8.gemfile
  gemfiles/sinatra.gemfile
  gemfiles/webmachine2.gemfile
Labels: chore
