Repository appsignal/appsignal-ruby, pull requests merged in 2025-07, with the labels that each got.

#1428 Update YARD documentation
  .changesets/improve-yard-documentation-for-public-apis-.md
  lib/appsignal.rb
  lib/appsignal/auth_check.rb
  lib/appsignal/config.rb
  lib/appsignal/custom_marker.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/helpers/metrics.rb
  lib/appsignal/probes.rb
  lib/appsignal/transaction.rb
  spec/lib/appsignal/auth_check_spec.rb
Labels: chore

#1432 Add CLAUDE.md file
  CLAUDE.md
Labels: chore

#1430 Read revision from the REVISION file
  .changesets/when-a-deployment-tool-provides-the-revision-file--appsignal-will-now-use-that-to-set-the-revision-config.md
  lib/appsignal/config.rb
  spec/lib/appsignal/config_spec.rb
Labels: feature

#1437 Improve YARD docs and signatures
  lib/appsignal.rb
  lib/appsignal/check_in.rb
  lib/appsignal/config.rb
  lib/appsignal/helpers/instrumentation.rb
  lib/appsignal/transaction.rb
  sig/appsignal.rbi
  sig/appsignal.rbs
Labels: enhancement

#1435 Change backtrace logging from debug to error level
  .changesets/updates-to-error-level-instead-of-debug-level-for-better-visibility-of-critical-failures-.md
  lib/appsignal/hooks.rb
  lib/appsignal/probes.rb
  spec/lib/appsignal/hooks_spec.rb
  spec/lib/appsignal/probes_spec.rb
Labels: chore

#1436 Merge Hash-like values in sample data
  .changesets/merge-metadata-when-comparing-hash-like-values-.md
  lib/appsignal/sample_data.rb
  spec/lib/appsignal/sample_data_spec.rb
Labels: bug

#1438 Include updated signatures in releases
  mono.yml
  sig/appsignal.rbi
Labels: chore
